import os
from collections import OrderedDict

"""

This module is all about constant value 

"""

DEBUG_MODE = True
#FULL_SYSTEM_TEST = True
FULL_SYSTEM_TEST = False
SLURM_MUTREP_TEST = False
SLURM_GATKBP_TEST = False
SLURM_CMMDB_TEST = False
SLURM_TEST = False

FAST_PROJECT_CODE = 'b2012247'
SLOW_PROJECT_CODE = 'b2011097'

ENV_TEST_DIR = "PYTHON_TEST_DIR"

## ************************************************************************************* GATK Best practice (DNA seq) *************************************************************************************
DNASEQ_PIPELINE_DESCRIPTION = "A flow to control a pipeline to process DNA sequencing data"
DNASEQ_PIPELINE_DFLT_LOG_FILE = "dnaseq_pipeline"
DFLT_GATKBP_ALLOC_TIME = "4-00:00:00"

DNASEQ_CREATE_JOB_SETUP_FILE_DESCRIPTION = "An applicationt to generate job setup file for DNASEQ_PIPELINE"

## ************************************************************************************************ CMM DB ************************************************************************************************
CMMDB_PIPELINE_DESCRIPTION = "A flow to control a pipeline to process CMM database"
CMMDB_MUTSTAT_DESCRIPTION = "A flow to control a pipeline to process mutation statistics database"
CMMDB_TABLEANNOVAR_DESCRIPTION = "A flow to control a pipeline to run tableannovar"
CMMDB_MUTATIONREPORTS_DESCRIPTION = "A flow to control a pipeline to run generate mutation reports"
CMMDB_PIPELINE_DFLT_LOG_FILE = "cmmdb_pipeline"
DFLT_CMMDB_ALLOC_TIME = "1-00:00:00"

CMMDB_CREATE_JOB_SETUP_FILE_DESCRIPTION = "An applicationt to generate job setup file to process CMM database"

## ******************************************************************************************* Mutation report ********************************************************************************************
MUTREP_FAMILY_REPORT_BIN = 'pyCMM-mutrep-family-report'
MUTREP_SUMMARY_REPORT_BIN = 'pyCMM-mutrep-summary-report'

MUTREP_PIPELINE_DESCRIPTION = "A flow to control a pipeline to process mutations report"
MUTREP_PIPELINE_DFLT_LOG_FILE = "mutrep_pipeline"
DFLT_MUTREP_ALLOC_TIME = "1-00:00:00"

MUTREP_FAMILY_REPORT_DESCRIPTION = "An appliation to generate mutation report for a given family at given regions"
MUTREP_SUMMARY_REPORT_DESCRIPTION = "An appliation to generate summary report at given regions"
MUTREP_CREATE_JOB_SETUP_FILE_DESCRIPTION = "An application to generate job setup file to process mutations report"

## > > > > > > > > > > > > > > > > > > > > > > > > > > Annovar DB configurations < < < < < < < < < < < < < < < < < < < < < < < < < <
DFLT_ANNOVAR_DB_FOLDER = "/glob/jessada/tools/annovar/humandb"
DFLT_ANNOVAR_DB_NAMES = "refGene"
DFLT_ANNOVAR_DB_OPS = "g"
DFLT_ANNOVAR_DB_NAMES += ",cytoBand"
DFLT_ANNOVAR_DB_OPS += ",r"
DFLT_ANNOVAR_DB_NAMES += ",genomicSuperDups"
DFLT_ANNOVAR_DB_OPS += ",r"
DFLT_ANNOVAR_DB_NAMES += ",esp6500siv2_all"
DFLT_ANNOVAR_DB_OPS += ",f"
DFLT_ANNOVAR_DB_NAMES += ",1000g2014oct_eur"
DFLT_ANNOVAR_DB_OPS += ",f"
DFLT_ANNOVAR_DB_NAMES += ",1000g2014oct_all"
DFLT_ANNOVAR_DB_OPS += ",f"
DFLT_ANNOVAR_DB_NAMES += ",snp138"
DFLT_ANNOVAR_DB_OPS += ",f"
DFLT_ANNOVAR_DB_NAMES += ",exac03"
DFLT_ANNOVAR_DB_OPS += ",f"
DFLT_ANNOVAR_DB_NAMES += ",cg69"
DFLT_ANNOVAR_DB_OPS += ",f"
DFLT_ANNOVAR_DB_NAMES += ",cosmic70"
DFLT_ANNOVAR_DB_OPS += ",f"
DFLT_ANNOVAR_DB_NAMES += ",nci60"
DFLT_ANNOVAR_DB_OPS += ",f"
DFLT_ANNOVAR_DB_NAMES += ",clinvar_20150330"
DFLT_ANNOVAR_DB_OPS += ",f"
#DFLT_ANNOVAR_DB_NAMES += ",mitimpact2"
#DFLT_ANNOVAR_DB_OPS += ",f"
DFLT_ANNOVAR_DB_NAMES += ",CMM_Ill_Br"
DFLT_ANNOVAR_DB_OPS += ",f"
DFLT_ANNOVAR_DB_NAMES += ",CMM_CRC_all"
DFLT_ANNOVAR_DB_OPS += ",f"
DFLT_ANNOVAR_DB_NAMES += ",CMM_CRC_CAFAM"
DFLT_ANNOVAR_DB_OPS += ",f"
DFLT_ANNOVAR_DB_NAMES += ",CMM_CRC_COLON"
DFLT_ANNOVAR_DB_OPS += ",f"
DFLT_ANNOVAR_DB_NAMES += ",CMM_CRC_CRC"
DFLT_ANNOVAR_DB_OPS += ",f"
DFLT_ANNOVAR_DB_NAMES += ",CMM_CRC_RECTAL"
DFLT_ANNOVAR_DB_OPS += ",f"
DFLT_ANNOVAR_DB_NAMES += ",CMM_PMS2_sporadic_fam24"
DFLT_ANNOVAR_DB_OPS += ",f"
DFLT_ANNOVAR_DB_NAMES += ",CMM_Axeq_chr3_6_14_18"
DFLT_ANNOVAR_DB_OPS += ",f"
DFLT_ANNOVAR_DB_NAMES += ",CMM_Axeq_chr5_19"
DFLT_ANNOVAR_DB_OPS += ",f"
DFLT_ANNOVAR_DB_NAMES += ",CMM_Axeq_chr9"
DFLT_ANNOVAR_DB_OPS += ",f"
DFLT_ANNOVAR_DB_NAMES += ",200_Danes"
DFLT_ANNOVAR_DB_OPS += ",f"
DFLT_ANNOVAR_DB_NAMES += ",249_Swedes"
DFLT_ANNOVAR_DB_OPS += ",f"
DFLT_ANNOVAR_DB_NAMES += ",ljb26_all"
DFLT_ANNOVAR_DB_OPS += ",f"

## > > > > > > > > > > > > > > > > > > > > > > > > > > Annotation columns < < < < < < < < < < < < < < < < < < < < < < < < < <
# This list will show all possible annotation columns (based on the dbs annotated by table_annovar.pl), in the INFO fields.
# Note. Defining CONSTANT var is for error detection purpose. It will raise exception if the constant is used without pre-defined value

# Columns group tags: Tags to define columns group. This is for exclusion purpose.
# Group of mitochondria-related columns
MT_COLS_TAG = "MT"
# Group of Axeq chr3, 6, 14, 18 columns
AXEQ_CHR3_6_14_18_COLS_TAG = "Axeq_chr3_6_14_18"
# Group of Axeq chr5, 19 columns
AXEQ_CHR5_19_COLS_TAG = "Axeq_chr5_19"
# Group of Axeq chr9 columns
AXEQ_CHR9_COLS_TAG = "Axeq_chr9"
# Group of CRC all 101 samples columns
CRC_101_COLS_TAG = "CRC_101"
# Group of CRC cancer-family samples columns
CRC_CAFAM_COLS_TAG = "CRC_CAFAM"
# Group of CRC colon-cancer samples columns
CRC_COLON_COLS_TAG = "CRC_Colon"
# Group of CRC rectal-cancer samples columns
CRC_RECTAL_COLS_TAG = "CRC_Rectal"
# Group of CRC colorectal-cancer samples columns
CRC_CRC_COLS_TAG = "CRC_CRC"
# a group of 30 breast-cancer samples sequenced by Illumina
ILL_BR_COLS_TAG = "ILL_BR"
# NK64 is a group of 64 samples sequenced in 2015 which consist of PMS2-, early onset-, and family24 samples
NK64_COLS_TAG = "NK64"
# Group of columns annotating detailed information of mutation stat
MUTSTAT_DETAILS_COLS_TAG = "Mutstat_details"
# Group of LJB score columns
LJB_SCORE_COLS_TAG = "LJB_score"
# Group of ExAC scores beside ExAC_ALL and ExAC_NFE
EXAC_OTH_COLS_TAG = "ExAC_Other"
# Group of columns that I don't really sure what it is about
UNKNOWN_COLS_TAG = "Unknown"

# Mitochondria-related columns
GENE_SYMBOL_COL_NAME = "Gene_symbol"
OXPHOS_COMPLEX_COL_NAME = "OXPHOS_Complex"
ENSEMBL_GENE_ID_COL_NAME = "Ensembl_Gene_ID"
ENSEMBL_PROTEIN_ID_COL_NAME = "Ensembl_Protein_ID"
UNIPROT_NAME_COL_NAME = "Uniprot_Name"
UNIPROT_ID_COL_NAME = "Uniprot_ID"
NCBI_GENE_ID_COL_NAME = "NCBI_Gene_ID"
NCBI_PROTEIN_ID_COL_NAME = "NCBI_Protein_ID"
GENE_POS_COL_NAME = "Gene_pos"
AA_POS_COL_NAME = "AA_pos"
AA_SUB_COL_NAME = "AA_sub"
CODON_SUB_COL_NAME = "Codon_sub"
DBSNP_ID_COL_NAME = "dbSNP_ID"
PHYLOP_46V_COL_NAME = "PhyloP_46V"
PHASTCONS_46V_COL_NAME = "PhastCons_46V"
PHYLOP_100V_COL_NAME = "PhyloP_100V"
PHASTCONS_100V_COL_NAME = "PhastCons_100V"
SITEVAR_COL_NAME = "SiteVar"
POLYPHEN2_PREDICTION_COL_NAME = "PolyPhen2_prediction"
POLYPHEN2_SCORE_COL_NAME = "PolyPhen2_score"
SIFT_PREDICTION_COL_NAME = "SIFT_prediction"
SIFT_SCORE_COL_NAME = "SIFT_score"
FATHMM_PREDICTION_COL_NAME = "FatHmm_prediction"
FATHMM_SCORE_COL_NAME = "FatHmm_score"
PROVEAN_PREDICTION_COL_NAME = "PROVEAN_prediction"
PROVEAN_SCORE_COL_NAME = "PROVEAN_score"
MUTASS_PREDICTION_COL_NAME = "MutAss_prediction"
MUTASS_SCORE_COL_NAME = "MutAss_score"
EFIN_SWISS_PROT_SCORE_COL_NAME = "EFIN_Swiss_Prot_Score"
EFIN_SWISS_PROT_PREDICTION_COL_NAME = "EFIN_Swiss_Prot_Prediction"
EFIN_HUMDIV_SCORE_COL_NAME = "EFIN_HumDiv_Score"
EFIN_HUMDIV_PREDICTION_COL_NAME = "EFIN_HumDiv_Prediction"
CADD_SCORE_COL_NAME = "CADD_score"
CADD_PHRED_SCORE_COL_NAME = "CADD_Phred_score"
CADD_PREDICTION_COL_NAME = "CADD_prediction"
CAROL_PREDICTION_COL_NAME = "Carol_prediction"
CAROL_SCORE_COL_NAME = "Carol_score"
CONDEL_SCORE_COL_NAME = "Condel_score"
CONDEL_PRED_COL_NAME = "Condel_pred"
COVEC_WMV_COL_NAME = "COVEC_WMV"
COVEC_WMV_PREDICTION_COL_NAME = "COVEC_WMV_prediction"
POLYPHEN2_SCORE_TRANSF_COL_NAME = "PolyPhen2_score_transf"
POLYPHEN2_PRED_TRANSF_COL_NAME = "PolyPhen2_pred_transf"
SIFT_SCORE_TRANSF_COL_NAME = "SIFT_score_transf"
SIFT_PRED_TRANSF_COL_NAME = "SIFT_pred_transf"
MUTASS_SCORE_TRANSF_COL_NAME = "MutAss_score_transf"
MUTASS_PRED_TRANSF_COL_NAME = "MutAss_pred_transf"
PERC_COEVO_SITES_COL_NAME = "Perc_coevo_Sites"
MEAN_MI_SCORE_COL_NAME = "Mean_MI_score"
COSMIC_ID_COL_NAME = "COSMIC_ID"
TUMOR_SITE_COL_NAME = "Tumor_site"
EXAMINED_SAMPLES_COL_NAME = "Examined_samples"
MUTATION_FREQUENCY_COL_NAME = "Mutation_frequency"
US_COL_NAME = "US"
STATUS_COL_NAME = "Status"
ASSOCIATED_DISEASE_COL_NAME = "Associated_disease"
PRESENCE_IN_TD_COL_NAME = "Presence_in_TD"
CLASS_PREDICTED_COL_NAME = "Class_predicted"
PROB_N_COL_NAME = "Prob_N"
PROB_P_COL_NAME = "Prob_P"

MT_ANNO_COLS = OrderedDict()
MT_ANNO_COLS[GENE_SYMBOL_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[OXPHOS_COMPLEX_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[ENSEMBL_GENE_ID_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[ENSEMBL_PROTEIN_ID_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[UNIPROT_NAME_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[UNIPROT_ID_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[NCBI_GENE_ID_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[NCBI_PROTEIN_ID_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[GENE_POS_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[AA_POS_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[AA_SUB_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[CODON_SUB_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[DBSNP_ID_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[PHYLOP_46V_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[PHASTCONS_46V_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[PHYLOP_100V_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[PHASTCONS_100V_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[SITEVAR_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[POLYPHEN2_PREDICTION_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[POLYPHEN2_SCORE_COL_NAME] = [MT_COLS_TAG]
#MT_ANNO_COLS[SIFT_PREDICTION_COL_NAME] = [MT_COLS_TAG]
#MT_ANNO_COLS[SIFT_SCORE_COL_NAME] = [MT_COLS_TAG]
#MT_ANNO_COLS[FATHMM_PREDICTION_COL_NAME] = [MT_COLS_TAG]
#MT_ANNO_COLS[FATHMM_SCORE_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[PROVEAN_PREDICTION_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[PROVEAN_SCORE_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[MUTASS_PREDICTION_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[MUTASS_SCORE_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[EFIN_SWISS_PROT_SCORE_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[EFIN_SWISS_PROT_PREDICTION_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[EFIN_HUMDIV_SCORE_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[EFIN_HUMDIV_PREDICTION_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[CADD_SCORE_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[CADD_PHRED_SCORE_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[CADD_PREDICTION_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[CAROL_PREDICTION_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[CAROL_SCORE_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[CONDEL_SCORE_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[CONDEL_PRED_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[COVEC_WMV_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[COVEC_WMV_PREDICTION_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[POLYPHEN2_SCORE_TRANSF_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[POLYPHEN2_PRED_TRANSF_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[SIFT_SCORE_TRANSF_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[SIFT_PRED_TRANSF_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[MUTASS_SCORE_TRANSF_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[MUTASS_PRED_TRANSF_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[PERC_COEVO_SITES_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[MEAN_MI_SCORE_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[COSMIC_ID_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[TUMOR_SITE_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[EXAMINED_SAMPLES_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[MUTATION_FREQUENCY_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[US_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[STATUS_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[ASSOCIATED_DISEASE_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[PRESENCE_IN_TD_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[CLASS_PREDICTED_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[PROB_N_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[PROB_P_COL_NAME] = [MT_COLS_TAG]

# Effect predictor columns
LJB_SIFT_PREDICTION_COL_NAME = "SIFT_pred"
LJB_POLYPHEN2_HDIV_PREDICTION_COL_NAME = "Polyphen2_HDIV_pred"
LJB_POLYPHEN2_HVAR_PREDICTION_COL_NAME = "Polyphen2_HVAR_pred"
LJB_LRT_PREDICTION_COL_NAME = "LRT_pred"
LJB_MUTATIONTASTER_PREDICTION_COL_NAME = "MutationTaster_pred"
LJB_MUTATIONASSESSOR_PREDICTION_COL_NAME = "MutationAssessor_pred"
LJB_FATHMM_PREDICTION_COL_NAME = "FATHMM_pred"
LJB_RADIALSVM_PREDICTION_COL_NAME = "RadialSVM_pred"
LJB_LR_PREDICTION_COL_NAME = "LR_pred"

PREDICTION_COLS = {}
PREDICTION_COLS[LJB_SIFT_PREDICTION_COL_NAME] = []
PREDICTION_COLS[LJB_POLYPHEN2_HDIV_PREDICTION_COL_NAME] = []
PREDICTION_COLS[LJB_POLYPHEN2_HVAR_PREDICTION_COL_NAME] = []
PREDICTION_COLS[LJB_LRT_PREDICTION_COL_NAME] = []
PREDICTION_COLS[LJB_MUTATIONTASTER_PREDICTION_COL_NAME] = []
PREDICTION_COLS[LJB_MUTATIONASSESSOR_PREDICTION_COL_NAME] = []
PREDICTION_COLS[LJB_FATHMM_PREDICTION_COL_NAME] = []
PREDICTION_COLS[LJB_RADIALSVM_PREDICTION_COL_NAME] = []
PREDICTION_COLS[LJB_LR_PREDICTION_COL_NAME] = []

# Other columns
FUNC_REFGENE_COL_NAME = "Func.refGene"
EXONICFUNC_REFGENE_COL_NAME = "ExonicFunc.refGene"
GENE_REFGENE_COL_NAME = "Gene.refGene"
GENEDETAIL_REFGENE_COL_NAME = "GeneDetail.refGene"
SNP138_COL_NAME = "snp138"
KG2014OCT_EUR_COL_NAME = "1000g2014oct_eur"
KG2014OCT_ALL_COL_NAME = "1000g2014oct_all"
ILL_BR_PF_COL_NAME = "ILL_BR_PF"
ILL_BR_GF_COL_NAME = "ILL_BR_GF"
CRC_ALL_PF_COL_NAME = "CRC_ALL_PF"
CRC_ALL_GF_COL_NAME = "CRC_ALL_GF"
PMS2_SPORADIC_FAM24_PF_COL_NAME = "PMS2_SPORADIC_FAM24_PF"
PMS2_SPORADIC_FAM24_GF_COL_NAME = "PMS2_SPORADIC_FAM24_GF"
AXEQ_CHR3_6_14_18_PF_COL_NAME = "AXEQ_CHR3_6_14_18_PF"
AXEQ_CHR3_6_14_18_GF_COL_NAME = "AXEQ_CHR3_6_14_18_GF"
AXEQ_CHR5_19_PF_COL_NAME = "AXEQ_CHR5_19_PF"
AXEQ_CHR5_19_GF_COL_NAME = "AXEQ_CHR5_19_GF"
AXEQ_CHR9_PF_COL_NAME = "AXEQ_CHR9_PF"
AXEQ_CHR9_GF_COL_NAME = "AXEQ_CHR9_GF"
SWEDES_COL_NAME = "249_SWEDES"
DANES_COL_NAME = "200_DANES"
EXAC_ALL_COL_NAME = "ExAC_ALL"
EXAC_AFR_COL_NAME = "ExAC_AFR"
EXAC_AMR_COL_NAME = "ExAC_AMR"
EXAC_EAS_COL_NAME = "ExAC_EAS"
EXAC_FIN_COL_NAME = "ExAC_FIN"
EXAC_NFE_COL_NAME = "ExAC_NFE"
EXAC_OTH_COL_NAME = "ExAC_OTH"
EXAC_SAS_COL_NAME = "ExAC_SAS"
AACHANGE_REFGENE_COL_NAME = "AAChange.refGene"
CYTOBAND_COL_NAME = "cytoBand"
GENOMICSUPERDUPS_COL_NAME = "genomicSuperDups"
ESP6500SIV2_ALL_COL_NAME = "esp6500siv2_all"
CG69_COL_NAME = "cg69"
COSMIC70_COL_NAME = "cosmic70"
NCI60_COL_NAME = "nci60"
CLINVAR_20150330_COL_NAME = "clinvar_20150330"
ILL_BR_WT_COL_NAME = "ILL_BR_WT"
ILL_BR_HET_COL_NAME = "ILL_BR_HET"
ILL_BR_HOM_COL_NAME = "ILL_BR_HOM"
ILL_BR_OTH_COL_NAME = "ILL_BR_OTH"
ILL_BR_NA_COL_NAME = "ILL_BR_NA"
ILL_BR_GT_COL_NAME = "ILL_BR_GT"
ILL_BR_AF_COL_NAME = "ILL_BR_AF"
CRC_ALL_WT_COL_NAME = "CRC_ALL_WT"
CRC_ALL_HET_COL_NAME = "CRC_ALL_HET"
CRC_ALL_HOM_COL_NAME = "CRC_ALL_HOM"
CRC_ALL_OTH_COL_NAME = "CRC_ALL_OTH"
CRC_ALL_NA_COL_NAME = "CRC_ALL_NA"
CRC_ALL_GT_COL_NAME = "CRC_ALL_GT"
CRC_ALL_AF_COL_NAME = "CRC_ALL_AF"
CRC_CAFAM_WT_COL_NAME = "CRC_CAFAM_WT"
CRC_CAFAM_HET_COL_NAME = "CRC_CAFAM_HET"
CRC_CAFAM_HOM_COL_NAME = "CRC_CAFAM_HOM"
CRC_CAFAM_OTH_COL_NAME = "CRC_CAFAM_OTH"
CRC_CAFAM_NA_COL_NAME = "CRC_CAFAM_NA"
CRC_CAFAM_GT_COL_NAME = "CRC_CAFAM_GT"
CRC_CAFAM_PF_COL_NAME = "CRC_CAFAM_PF"
CRC_CAFAM_AF_COL_NAME = "CRC_CAFAM_AF"
CRC_CAFAM_GF_COL_NAME = "CRC_CAFAM_GF"
CRC_COLON_WT_COL_NAME = "CRC_COLON_WT"
CRC_COLON_HET_COL_NAME = "CRC_COLON_HET"
CRC_COLON_HOM_COL_NAME = "CRC_COLON_HOM"
CRC_COLON_OTH_COL_NAME = "CRC_COLON_OTH"
CRC_COLON_NA_COL_NAME = "CRC_COLON_NA"
CRC_COLON_GT_COL_NAME = "CRC_COLON_GT"
CRC_COLON_PF_COL_NAME = "CRC_COLON_PF"
CRC_COLON_AF_COL_NAME = "CRC_COLON_AF"
CRC_COLON_GF_COL_NAME = "CRC_COLON_GF"
CRC_CRC_WT_COL_NAME = "CRC_CRC_WT"
CRC_CRC_HET_COL_NAME = "CRC_CRC_HET"
CRC_CRC_HOM_COL_NAME = "CRC_CRC_HOM"
CRC_CRC_OTH_COL_NAME = "CRC_CRC_OTH"
CRC_CRC_NA_COL_NAME = "CRC_CRC_NA"
CRC_CRC_GT_COL_NAME = "CRC_CRC_GT"
CRC_CRC_PF_COL_NAME = "CRC_CRC_PF"
CRC_CRC_AF_COL_NAME = "CRC_CRC_AF"
CRC_CRC_GF_COL_NAME = "CRC_CRC_GF"
CRC_RECTAL_WT_COL_NAME = "CRC_RECTAL_WT"
CRC_RECTAL_HET_COL_NAME = "CRC_RECTAL_HET"
CRC_RECTAL_HOM_COL_NAME = "CRC_RECTAL_HOM"
CRC_RECTAL_OTH_COL_NAME = "CRC_RECTAL_OTH"
CRC_RECTAL_NA_COL_NAME = "CRC_RECTAL_NA"
CRC_RECTAL_GT_COL_NAME = "CRC_RECTAL_GT"
CRC_RECTAL_PF_COL_NAME = "CRC_RECTAL_PF"
CRC_RECTAL_AF_COL_NAME = "CRC_RECTAL_AF"
CRC_RECTAL_GF_COL_NAME = "CRC_RECTAL_GF"
PMS2_SPORADIC_FAM24_WT_COL_NAME = "PMS2_SPORADIC_FAM24_WT"
PMS2_SPORADIC_FAM24_HET_COL_NAME = "PMS2_SPORADIC_FAM24_HET"
PMS2_SPORADIC_FAM24_HOM_COL_NAME = "PMS2_SPORADIC_FAM24_HOM"
PMS2_SPORADIC_FAM24_OTH_COL_NAME = "PMS2_SPORADIC_FAM24_OTH"
PMS2_SPORADIC_FAM24_NA_COL_NAME = "PMS2_SPORADIC_FAM24_NA"
PMS2_SPORADIC_FAM24_GT_COL_NAME = "PMS2_SPORADIC_FAM24_GT"
PMS2_SPORADIC_FAM24_AF_COL_NAME = "PMS2_SPORADIC_FAM24_AF"
AXEQ_CHR3_6_14_18_WT_COL_NAME = "AXEQ_CHR3_6_14_18_WT"
AXEQ_CHR3_6_14_18_HET_COL_NAME = "AXEQ_CHR3_6_14_18_HET"
AXEQ_CHR3_6_14_18_HOM_COL_NAME = "AXEQ_CHR3_6_14_18_HOM"
AXEQ_CHR3_6_14_18_OTH_COL_NAME = "AXEQ_CHR3_6_14_18_OTH"
AXEQ_CHR3_6_14_18_NA_COL_NAME = "AXEQ_CHR3_6_14_18_NA"
AXEQ_CHR3_6_14_18_GT_COL_NAME = "AXEQ_CHR3_6_14_18_GT"
AXEQ_CHR3_6_14_18_AF_COL_NAME = "AXEQ_CHR3_6_14_18_AF"
AXEQ_CHR5_19_WT_COL_NAME = "AXEQ_CHR5_19_WT"
AXEQ_CHR5_19_HET_COL_NAME = "AXEQ_CHR5_19_HET"
AXEQ_CHR5_19_HOM_COL_NAME = "AXEQ_CHR5_19_HOM"
AXEQ_CHR5_19_OTH_COL_NAME = "AXEQ_CHR5_19_OTH"
AXEQ_CHR5_19_NA_COL_NAME = "AXEQ_CHR5_19_NA"
AXEQ_CHR5_19_GT_COL_NAME = "AXEQ_CHR5_19_GT"
AXEQ_CHR5_19_AF_COL_NAME = "AXEQ_CHR5_19_AF"
AXEQ_CHR9_WT_COL_NAME = "AXEQ_CHR9_WT"
AXEQ_CHR9_HET_COL_NAME = "AXEQ_CHR9_HET"
AXEQ_CHR9_HOM_COL_NAME = "AXEQ_CHR9_HOM"
AXEQ_CHR9_OTH_COL_NAME = "AXEQ_CHR9_OTH"
AXEQ_CHR9_NA_COL_NAME = "AXEQ_CHR9_NA"
AXEQ_CHR9_GT_COL_NAME = "AXEQ_CHR9_GT"
AXEQ_CHR9_AF_COL_NAME = "AXEQ_CHR9_AF"
SIFT_SCORE_COL_NAME = "SIFT_score"
POLYPHEN2_HDIV_SCORE_COL_NAME = "Polyphen2_HDIV_score"
POLYPHEN2_HVAR_SCORE_COL_NAME = "Polyphen2_HVAR_score"
LRT_SCORE_COL_NAME = "LRT_score"
MUTATIONTASTER_SCORE_COL_NAME = "MutationTaster_score"
MUTATIONASSESSOR_SCORE_COL_NAME = "MutationAssessor_score"
FATHMM_SCORE_COL_NAME = "FATHMM_score"
RADIALSVM_SCORE_COL_NAME = "RadialSVM_score"
LR_SCORE_COL_NAME = "LR_score"
VEST3_SCORE_COL_NAME = "VEST3_score"
CADD_RAW_COL_NAME = "CADD_raw"
CADD_PHRED_COL_NAME = "CADD_phred"
GERP_RS_COL_NAME = "GERP++_RS"
PHYLOP46WAY_PLACENTAL_COL_NAME = "phyloP46way_placental"
PHYLOP100WAY_VERTEBRATE_COL_NAME = "phyloP100way_vertebrate"
SIPHY_29WAY_LOGODDS_COL_NAME = "SiPhy_29way_logOdds"

PRIMARY_MAF_VAR = KG2014OCT_ALL_COL_NAME
DFLT_MUTREP_FREQ_RATIOS = PRIMARY_MAF_VAR + ":0.2"
FUNC_REFGENE_VAR = FUNC_REFGENE_COL_NAME
EXONICFUNC_REFGENE_VAR = EXONICFUNC_REFGENE_COL_NAME

ALL_MUTREP_ANNO_COLS = OrderedDict()
ALL_MUTREP_ANNO_COLS[FUNC_REFGENE_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[EXONICFUNC_REFGENE_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[GENE_REFGENE_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[GENEDETAIL_REFGENE_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[SNP138_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[KG2014OCT_EUR_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[KG2014OCT_ALL_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[ILL_BR_PF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[ILL_BR_GF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_ALL_PF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_ALL_GF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[PMS2_SPORADIC_FAM24_PF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[PMS2_SPORADIC_FAM24_GF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR3_6_14_18_PF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR3_6_14_18_GF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR5_19_PF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR5_19_GF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR9_PF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR9_GF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[SWEDES_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[DANES_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[EXAC_ALL_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[EXAC_AFR_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[EXAC_AMR_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[EXAC_EAS_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[EXAC_FIN_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[EXAC_NFE_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[EXAC_OTH_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[EXAC_SAS_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AACHANGE_REFGENE_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CYTOBAND_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[GENOMICSUPERDUPS_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[ESP6500SIV2_ALL_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CG69_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[COSMIC70_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[NCI60_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CLINVAR_20150330_COL_NAME] = []
#ALL_MUTREP_ANNO_COLS.update(MT_ANNO_COLS)
ALL_MUTREP_ANNO_COLS[ILL_BR_WT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[ILL_BR_HET_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[ILL_BR_HOM_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[ILL_BR_OTH_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[ILL_BR_NA_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[ILL_BR_GT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[ILL_BR_AF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_ALL_WT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_ALL_HET_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_ALL_HOM_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_ALL_OTH_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_ALL_NA_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_ALL_GT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_ALL_AF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_CAFAM_WT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_CAFAM_HET_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_CAFAM_HOM_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_CAFAM_OTH_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_CAFAM_NA_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_CAFAM_GT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_CAFAM_PF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_CAFAM_AF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_CAFAM_GF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_COLON_WT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_COLON_HET_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_COLON_HOM_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_COLON_OTH_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_COLON_NA_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_COLON_GT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_COLON_PF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_COLON_AF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_COLON_GF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_CRC_WT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_CRC_HET_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_CRC_HOM_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_CRC_OTH_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_CRC_NA_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_CRC_GT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_CRC_PF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_CRC_AF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_CRC_GF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_RECTAL_WT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_RECTAL_HET_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_RECTAL_HOM_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_RECTAL_OTH_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_RECTAL_NA_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_RECTAL_GT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_RECTAL_PF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_RECTAL_AF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CRC_RECTAL_GF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[PMS2_SPORADIC_FAM24_WT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[PMS2_SPORADIC_FAM24_HET_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[PMS2_SPORADIC_FAM24_HOM_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[PMS2_SPORADIC_FAM24_OTH_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[PMS2_SPORADIC_FAM24_NA_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[PMS2_SPORADIC_FAM24_GT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[PMS2_SPORADIC_FAM24_AF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR3_6_14_18_WT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR3_6_14_18_HET_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR3_6_14_18_HOM_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR3_6_14_18_OTH_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR3_6_14_18_NA_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR3_6_14_18_GT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR3_6_14_18_AF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR5_19_WT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR5_19_HET_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR5_19_HOM_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR5_19_OTH_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR5_19_NA_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR5_19_GT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR5_19_AF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR9_WT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR9_HET_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR9_HOM_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR9_OTH_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR9_NA_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR9_GT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR9_AF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[SIFT_SCORE_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[LJB_SIFT_PREDICTION_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[POLYPHEN2_HDIV_SCORE_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[LJB_POLYPHEN2_HDIV_PREDICTION_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[POLYPHEN2_HVAR_SCORE_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[LJB_POLYPHEN2_HVAR_PREDICTION_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[LRT_SCORE_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[LJB_LRT_PREDICTION_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[MUTATIONTASTER_SCORE_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[LJB_MUTATIONTASTER_PREDICTION_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[MUTATIONASSESSOR_SCORE_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[LJB_MUTATIONASSESSOR_PREDICTION_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[FATHMM_SCORE_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[LJB_FATHMM_PREDICTION_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[RADIALSVM_SCORE_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[LJB_RADIALSVM_PREDICTION_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[LR_SCORE_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[LJB_LR_PREDICTION_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[VEST3_SCORE_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CADD_RAW_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CADD_PHRED_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[GERP_RS_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[PHYLOP46WAY_PLACENTAL_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[PHYLOP100WAY_VERTEBRATE_COL_NAME] = []

# set tags
cols_tags = {}
# set columns associated with AXEQ_CHR3_6_14_18_COLS_TAG
cols_tags[AXEQ_CHR3_6_14_18_COLS_TAG] = []
cols_tags[AXEQ_CHR3_6_14_18_COLS_TAG].append(AXEQ_CHR3_6_14_18_WT_COL_NAME)
cols_tags[AXEQ_CHR3_6_14_18_COLS_TAG].append(AXEQ_CHR3_6_14_18_HET_COL_NAME)
cols_tags[AXEQ_CHR3_6_14_18_COLS_TAG].append(AXEQ_CHR3_6_14_18_HOM_COL_NAME)
cols_tags[AXEQ_CHR3_6_14_18_COLS_TAG].append(AXEQ_CHR3_6_14_18_OTH_COL_NAME)
cols_tags[AXEQ_CHR3_6_14_18_COLS_TAG].append(AXEQ_CHR3_6_14_18_NA_COL_NAME)
cols_tags[AXEQ_CHR3_6_14_18_COLS_TAG].append(AXEQ_CHR3_6_14_18_GT_COL_NAME)
cols_tags[AXEQ_CHR3_6_14_18_COLS_TAG].append(AXEQ_CHR3_6_14_18_AF_COL_NAME)
cols_tags[AXEQ_CHR3_6_14_18_COLS_TAG].append(AXEQ_CHR3_6_14_18_PF_COL_NAME)
cols_tags[AXEQ_CHR3_6_14_18_COLS_TAG].append(AXEQ_CHR3_6_14_18_GF_COL_NAME)

# set columns associated with AXEQ_CHR5_19_COLS_TAG
cols_tags[AXEQ_CHR5_19_COLS_TAG] = []
cols_tags[AXEQ_CHR5_19_COLS_TAG].append(AXEQ_CHR5_19_WT_COL_NAME)
cols_tags[AXEQ_CHR5_19_COLS_TAG].append(AXEQ_CHR5_19_HET_COL_NAME)
cols_tags[AXEQ_CHR5_19_COLS_TAG].append(AXEQ_CHR5_19_HOM_COL_NAME)
cols_tags[AXEQ_CHR5_19_COLS_TAG].append(AXEQ_CHR5_19_OTH_COL_NAME)
cols_tags[AXEQ_CHR5_19_COLS_TAG].append(AXEQ_CHR5_19_NA_COL_NAME)
cols_tags[AXEQ_CHR5_19_COLS_TAG].append(AXEQ_CHR5_19_GT_COL_NAME)
cols_tags[AXEQ_CHR5_19_COLS_TAG].append(AXEQ_CHR5_19_AF_COL_NAME)
cols_tags[AXEQ_CHR5_19_COLS_TAG].append(AXEQ_CHR5_19_PF_COL_NAME)
cols_tags[AXEQ_CHR5_19_COLS_TAG].append(AXEQ_CHR5_19_GF_COL_NAME)

# set columns associated with AXEQ_CHR9_COLS_TAG
cols_tags[AXEQ_CHR9_COLS_TAG] = []
cols_tags[AXEQ_CHR9_COLS_TAG].append(AXEQ_CHR9_WT_COL_NAME)
cols_tags[AXEQ_CHR9_COLS_TAG].append(AXEQ_CHR9_HET_COL_NAME)
cols_tags[AXEQ_CHR9_COLS_TAG].append(AXEQ_CHR9_HOM_COL_NAME)
cols_tags[AXEQ_CHR9_COLS_TAG].append(AXEQ_CHR9_OTH_COL_NAME)
cols_tags[AXEQ_CHR9_COLS_TAG].append(AXEQ_CHR9_NA_COL_NAME)
cols_tags[AXEQ_CHR9_COLS_TAG].append(AXEQ_CHR9_GT_COL_NAME)
cols_tags[AXEQ_CHR9_COLS_TAG].append(AXEQ_CHR9_AF_COL_NAME)
cols_tags[AXEQ_CHR9_COLS_TAG].append(AXEQ_CHR9_PF_COL_NAME)
cols_tags[AXEQ_CHR9_COLS_TAG].append(AXEQ_CHR9_GF_COL_NAME)

# set columns associated with CRC_101_COLS_TAG
cols_tags[CRC_101_COLS_TAG] = []
cols_tags[CRC_101_COLS_TAG].append(CRC_ALL_WT_COL_NAME)
cols_tags[CRC_101_COLS_TAG].append(CRC_ALL_HET_COL_NAME)
cols_tags[CRC_101_COLS_TAG].append(CRC_ALL_HOM_COL_NAME)
cols_tags[CRC_101_COLS_TAG].append(CRC_ALL_OTH_COL_NAME)
cols_tags[CRC_101_COLS_TAG].append(CRC_ALL_NA_COL_NAME)
cols_tags[CRC_101_COLS_TAG].append(CRC_ALL_GT_COL_NAME)
cols_tags[CRC_101_COLS_TAG].append(CRC_ALL_AF_COL_NAME)
cols_tags[CRC_101_COLS_TAG].append(CRC_ALL_PF_COL_NAME)
cols_tags[CRC_101_COLS_TAG].append(CRC_ALL_GF_COL_NAME)

# set columns associated with CRC_CAFAM_COLS_TAG
cols_tags[CRC_CAFAM_COLS_TAG] = []
cols_tags[CRC_CAFAM_COLS_TAG].append(CRC_CAFAM_WT_COL_NAME)
cols_tags[CRC_CAFAM_COLS_TAG].append(CRC_CAFAM_HET_COL_NAME)
cols_tags[CRC_CAFAM_COLS_TAG].append(CRC_CAFAM_HOM_COL_NAME)
cols_tags[CRC_CAFAM_COLS_TAG].append(CRC_CAFAM_OTH_COL_NAME)
cols_tags[CRC_CAFAM_COLS_TAG].append(CRC_CAFAM_NA_COL_NAME)
cols_tags[CRC_CAFAM_COLS_TAG].append(CRC_CAFAM_GT_COL_NAME)
cols_tags[CRC_CAFAM_COLS_TAG].append(CRC_CAFAM_AF_COL_NAME)
cols_tags[CRC_CAFAM_COLS_TAG].append(CRC_CAFAM_PF_COL_NAME)
cols_tags[CRC_CAFAM_COLS_TAG].append(CRC_CAFAM_GF_COL_NAME)

# set columns associated with CRC_COLON_COLS_TAG
cols_tags[CRC_COLON_COLS_TAG] = []
cols_tags[CRC_COLON_COLS_TAG].append(CRC_COLON_WT_COL_NAME)
cols_tags[CRC_COLON_COLS_TAG].append(CRC_COLON_HET_COL_NAME)
cols_tags[CRC_COLON_COLS_TAG].append(CRC_COLON_HOM_COL_NAME)
cols_tags[CRC_COLON_COLS_TAG].append(CRC_COLON_OTH_COL_NAME)
cols_tags[CRC_COLON_COLS_TAG].append(CRC_COLON_NA_COL_NAME)
cols_tags[CRC_COLON_COLS_TAG].append(CRC_COLON_GT_COL_NAME)
cols_tags[CRC_COLON_COLS_TAG].append(CRC_COLON_AF_COL_NAME)
cols_tags[CRC_COLON_COLS_TAG].append(CRC_COLON_PF_COL_NAME)
cols_tags[CRC_COLON_COLS_TAG].append(CRC_COLON_GF_COL_NAME)

# set columns associated with CRC_RECTAL_COLS_TAG
cols_tags[CRC_RECTAL_COLS_TAG] = []
cols_tags[CRC_RECTAL_COLS_TAG].append(CRC_RECTAL_WT_COL_NAME)
cols_tags[CRC_RECTAL_COLS_TAG].append(CRC_RECTAL_HET_COL_NAME)
cols_tags[CRC_RECTAL_COLS_TAG].append(CRC_RECTAL_HOM_COL_NAME)
cols_tags[CRC_RECTAL_COLS_TAG].append(CRC_RECTAL_OTH_COL_NAME)
cols_tags[CRC_RECTAL_COLS_TAG].append(CRC_RECTAL_NA_COL_NAME)
cols_tags[CRC_RECTAL_COLS_TAG].append(CRC_RECTAL_GT_COL_NAME)
cols_tags[CRC_RECTAL_COLS_TAG].append(CRC_RECTAL_AF_COL_NAME)
cols_tags[CRC_RECTAL_COLS_TAG].append(CRC_RECTAL_PF_COL_NAME)
cols_tags[CRC_RECTAL_COLS_TAG].append(CRC_RECTAL_GF_COL_NAME)

# set columns associated with CRC_CRC_COLS_TAG
cols_tags[CRC_CRC_COLS_TAG] = []
cols_tags[CRC_CRC_COLS_TAG].append(CRC_CRC_WT_COL_NAME)
cols_tags[CRC_CRC_COLS_TAG].append(CRC_CRC_HET_COL_NAME)
cols_tags[CRC_CRC_COLS_TAG].append(CRC_CRC_HOM_COL_NAME)
cols_tags[CRC_CRC_COLS_TAG].append(CRC_CRC_OTH_COL_NAME)
cols_tags[CRC_CRC_COLS_TAG].append(CRC_CRC_NA_COL_NAME)
cols_tags[CRC_CRC_COLS_TAG].append(CRC_CRC_GT_COL_NAME)
cols_tags[CRC_CRC_COLS_TAG].append(CRC_CRC_AF_COL_NAME)
cols_tags[CRC_CRC_COLS_TAG].append(CRC_CRC_PF_COL_NAME)
cols_tags[CRC_CRC_COLS_TAG].append(CRC_CRC_GF_COL_NAME)

# set columns associated with ILL_BR_COLS_TAG
cols_tags[ILL_BR_COLS_TAG] = []
cols_tags[ILL_BR_COLS_TAG].append(ILL_BR_WT_COL_NAME)
cols_tags[ILL_BR_COLS_TAG].append(ILL_BR_HET_COL_NAME)
cols_tags[ILL_BR_COLS_TAG].append(ILL_BR_HOM_COL_NAME)
cols_tags[ILL_BR_COLS_TAG].append(ILL_BR_OTH_COL_NAME)
cols_tags[ILL_BR_COLS_TAG].append(ILL_BR_NA_COL_NAME)
cols_tags[ILL_BR_COLS_TAG].append(ILL_BR_GT_COL_NAME)
cols_tags[ILL_BR_COLS_TAG].append(ILL_BR_AF_COL_NAME)
cols_tags[ILL_BR_COLS_TAG].append(ILL_BR_PF_COL_NAME)
cols_tags[ILL_BR_COLS_TAG].append(ILL_BR_GF_COL_NAME)

# set columns associated with NK64_COLS_TAG
cols_tags[NK64_COLS_TAG] = []
cols_tags[NK64_COLS_TAG].append(PMS2_SPORADIC_FAM24_WT_COL_NAME)
cols_tags[NK64_COLS_TAG].append(PMS2_SPORADIC_FAM24_HET_COL_NAME)
cols_tags[NK64_COLS_TAG].append(PMS2_SPORADIC_FAM24_HOM_COL_NAME)
cols_tags[NK64_COLS_TAG].append(PMS2_SPORADIC_FAM24_OTH_COL_NAME)
cols_tags[NK64_COLS_TAG].append(PMS2_SPORADIC_FAM24_NA_COL_NAME)
cols_tags[NK64_COLS_TAG].append(PMS2_SPORADIC_FAM24_GT_COL_NAME)
cols_tags[NK64_COLS_TAG].append(PMS2_SPORADIC_FAM24_AF_COL_NAME)
cols_tags[NK64_COLS_TAG].append(PMS2_SPORADIC_FAM24_PF_COL_NAME)
cols_tags[NK64_COLS_TAG].append(PMS2_SPORADIC_FAM24_GF_COL_NAME)

# set columns associated with MUTSTAT_DETAILS_COLS_TAG
cols_tags[MUTSTAT_DETAILS_COLS_TAG] = []
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR3_6_14_18_WT_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR3_6_14_18_HET_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR3_6_14_18_HOM_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR3_6_14_18_OTH_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR3_6_14_18_NA_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR3_6_14_18_GT_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR3_6_14_18_AF_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR5_19_WT_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR5_19_HET_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR5_19_HOM_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR5_19_OTH_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR5_19_NA_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR5_19_GT_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR5_19_AF_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR9_WT_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR9_HET_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR9_HOM_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR9_OTH_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR9_NA_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR9_GT_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR9_AF_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(CRC_ALL_WT_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(CRC_ALL_HET_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(CRC_ALL_HOM_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(CRC_ALL_OTH_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(CRC_ALL_NA_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(CRC_ALL_GT_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(CRC_ALL_AF_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(CRC_CAFAM_WT_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(CRC_CAFAM_HET_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(CRC_CAFAM_HOM_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(CRC_CAFAM_OTH_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(CRC_CAFAM_NA_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(CRC_CAFAM_GT_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(CRC_CAFAM_AF_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(CRC_COLON_WT_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(CRC_COLON_HET_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(CRC_COLON_HOM_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(CRC_COLON_OTH_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(CRC_COLON_NA_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(CRC_COLON_GT_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(CRC_COLON_AF_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(CRC_RECTAL_WT_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(CRC_RECTAL_HET_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(CRC_RECTAL_HOM_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(CRC_RECTAL_OTH_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(CRC_RECTAL_NA_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(CRC_RECTAL_GT_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(CRC_RECTAL_AF_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(CRC_CRC_WT_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(CRC_CRC_HET_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(CRC_CRC_HOM_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(CRC_CRC_OTH_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(CRC_CRC_NA_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(CRC_CRC_GT_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(CRC_CRC_AF_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(ILL_BR_WT_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(ILL_BR_HET_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(ILL_BR_HOM_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(ILL_BR_OTH_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(ILL_BR_NA_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(ILL_BR_GT_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(ILL_BR_AF_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(PMS2_SPORADIC_FAM24_WT_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(PMS2_SPORADIC_FAM24_HET_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(PMS2_SPORADIC_FAM24_HOM_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(PMS2_SPORADIC_FAM24_OTH_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(PMS2_SPORADIC_FAM24_NA_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(PMS2_SPORADIC_FAM24_GT_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(PMS2_SPORADIC_FAM24_AF_COL_NAME)

# set columns associated with LJB_SCORE_COLS_TAG
cols_tags[LJB_SCORE_COLS_TAG] = []
cols_tags[LJB_SCORE_COLS_TAG].append(SIFT_SCORE_COL_NAME)
cols_tags[LJB_SCORE_COLS_TAG].append(POLYPHEN2_HDIV_SCORE_COL_NAME)
cols_tags[LJB_SCORE_COLS_TAG].append(POLYPHEN2_HVAR_SCORE_COL_NAME)
cols_tags[LJB_SCORE_COLS_TAG].append(LRT_SCORE_COL_NAME)
cols_tags[LJB_SCORE_COLS_TAG].append(MUTATIONTASTER_SCORE_COL_NAME)
cols_tags[LJB_SCORE_COLS_TAG].append(MUTATIONASSESSOR_SCORE_COL_NAME)
cols_tags[LJB_SCORE_COLS_TAG].append(FATHMM_SCORE_COL_NAME)
cols_tags[LJB_SCORE_COLS_TAG].append(RADIALSVM_SCORE_COL_NAME)
cols_tags[LJB_SCORE_COLS_TAG].append(LR_SCORE_COL_NAME)

# set columns associated with EXAC_OTH_COLS_TAG
cols_tags[EXAC_OTH_COLS_TAG] = []
cols_tags[EXAC_OTH_COLS_TAG].append(EXAC_AFR_COL_NAME)
cols_tags[EXAC_OTH_COLS_TAG].append(EXAC_AMR_COL_NAME)
cols_tags[EXAC_OTH_COLS_TAG].append(EXAC_EAS_COL_NAME)
cols_tags[EXAC_OTH_COLS_TAG].append(EXAC_FIN_COL_NAME)
cols_tags[EXAC_OTH_COLS_TAG].append(EXAC_OTH_COL_NAME)
cols_tags[EXAC_OTH_COLS_TAG].append(EXAC_SAS_COL_NAME)

# set columns associated with EXAC_OTH_COLS_TAG
cols_tags[UNKNOWN_COLS_TAG] = []
cols_tags[UNKNOWN_COLS_TAG].append(GENOMICSUPERDUPS_COL_NAME)
cols_tags[UNKNOWN_COLS_TAG].append(VEST3_SCORE_COL_NAME)
cols_tags[UNKNOWN_COLS_TAG].append(CADD_RAW_COL_NAME)
cols_tags[UNKNOWN_COLS_TAG].append(CADD_PHRED_COL_NAME)
cols_tags[UNKNOWN_COLS_TAG].append(GERP_RS_COL_NAME)
cols_tags[UNKNOWN_COLS_TAG].append(PHYLOP46WAY_PLACENTAL_COL_NAME)
cols_tags[UNKNOWN_COLS_TAG].append(PHYLOP100WAY_VERTEBRATE_COL_NAME)

# assign all tags to all related columns
for cols_tag in cols_tags:
    col_names = cols_tags[cols_tag]
    for col_name in col_names:
        ALL_MUTREP_ANNO_COLS[col_name].append(cols_tag)
