import os
from collections import OrderedDict

"""

This module is all about constant value 

"""

## *********************************************************************************** Testing configuration  ************************************************************************************
DEBUG_MODE = True
FULL_SYSTEM_TEST = False
SLURM_TEST = False
XLS_TEST = False

TEST_PROJECT_CODE = 'b2012247'

ENV_TEST_DIR = "PYTHON_TEST_DIR"

## *********************************************************************************** General configuration  ************************************************************************************
DFLT_JOB_ALLOC_TIME = "4-00:00:00"
PHENOTYPE_MISSING = 0
PHENOTYPE_UNAFFECTED = 1
PHENOTYPE_AFFECTED = 2

## ************************************************************************************* GATK Best practice (DNA seq) *************************************************************************************
DNASEQ_SLURM_MONITOR_PIPELINE_BIN = 'pyCMM-dnaseq-slurm-monitor-pipeline'
DNASEQ_PIPELINE_DESCRIPTION = "A flow to control a pipeline to process DNA sequencing data"
DNASEQ_PIPELINE_DFLT_LOG_FILE = "dnaseq_pipeline"

DNASEQ_CREATE_JOB_SETUP_FILE_DESCRIPTION = "An applicationt to generate job setup file for DNASEQ_PIPELINE"

## ************************************************************************************************ CMM DB ************************************************************************************************
DUMMY_TABLE_ANNOVAR_BIN = 'pyCMM-dummy-table-annovar'
DUMMY_TABLE_ANNOVAR_BASH = "$PYCMM/bash/table_annovar_dummy.sh"

CMMDB_PIPELINE_DESCRIPTION = "A flow to control a pipeline to process CMM database"
CMMDB_MUTSTAT_DESCRIPTION = "A flow to control a pipeline to process mutation statistics database"
CMMDB_VCFAF2ANNOVAR_DESCRIPTION = "A flow to parse muation statistics from vcf format into annovar format"
CMMDB_TABLEANNOVAR_DESCRIPTION = "A flow to control a pipeline to run tableannovar"
CMMDB_MUTATIONREPORTS_DESCRIPTION = "A flow to control a pipeline to run generate mutation reports"
CMMDB_PIPELINE_DFLT_LOG_FILE = "cmmdb_pipeline"

CMMDB_CREATE_JOB_SETUP_FILE_DESCRIPTION = "An applicationt to generate job setup file to process CMM database"

## ******************************************************************************************* Mutation report ********************************************************************************************
MUTREP_SLURM_MONITOR_PIPELINE_BIN = 'pyCMM-mutrep-slurm-monitor-pipeline'
MUTREP_FAMILY_REPORT_BIN = 'pyCMM-mutrep-family-report'
MUTREP_SUMMARY_REPORT_BIN = 'pyCMM-mutrep-summary-report'

MUTREP_PIPELINE_DESCRIPTION = "A flow to control a pipeline to process mutations report"
MUTREP_PIPELINE_DFLT_LOG_FILE = "mutrep_pipeline"

MUTREP_FAMILY_REPORT_DESCRIPTION = "An appliation to generate mutation report for a given family at given regions"
MUTREP_SUMMARY_REPORT_DESCRIPTION = "An appliation to generate summary report at given regions"
MUTREP_CREATE_JOB_SETUP_FILE_DESCRIPTION = "An application to generate job setup file to process mutations report"

## ******************************************************************************************* DBMS ********************************************************************************************
#MUTREP_SLURM_MONITOR_PIPELINE_BIN = 'pyCMM-mutrep-slurm-monitor-pipeline'
#MUTREP_FAMILY_REPORT_BIN = 'pyCMM-mutrep-family-report'
#MUTREP_SUMMARY_REPORT_BIN = 'pyCMM-mutrep-summary-report'
#
#MUTREP_PIPELINE_DESCRIPTION = "A flow to control a pipeline to process mutations report"
#MUTREP_PIPELINE_DFLT_LOG_FILE = "mutrep_pipeline"
#
#MUTREP_FAMILY_REPORT_DESCRIPTION = "An appliation to generate mutation report for a given family at given regions"
DBMS_EXECUTE_DB_JOBS_DESCRIPTION = "An appliation to execute jobs related to SQLite DB"
DBMS_CREATE_JOB_SETUP_FILE_DESCRIPTION = "An application to generate job setup file to handle database management"

## *********************************************************************************************** PLINK *************************************************************************************************
PLINK_SLURM_MONITOR_PIPELINE_BIN = 'pyCMM-plink-slurm-monitor-pipeline'
PLINK_PIPELINE_DESCRIPTION = "A flow to control a PLINK haplotype association study"
PLINK_MERGE_HAP_ASSOCS_BIN = 'pyCMM-plink-merge-hap-assocs'
PLINK_HAP_ASSOCS_REPORT_BIN = 'pyCMM-plink-hap-assocs-report'

PLINK_PIPELINE_DESCRIPTION = "A flow to control a PLINK haplotype association study"
PLINK_MERGE_HAP_ASSOCS_DESCRIPTION = "An applciation to merge raw Plink haplotype association study results"
PLINK_HAP_ASSOCS_REPORT_DESCRIPTION = "A flow to generate haplotype association study report"
#PLINK_PIPELINE_DESCRIPTION = "A flow to control a PLINK pipeline"
PLINK_PIPELINE_DFLT_LOG_FILE = "plink_pipeline"

PLINK_CREATE_JOB_SETUP_FILE_DESCRIPTION = "An application to generate job setup file to run PLINK and generate report"

## > > > > > > > > > > > > > > > > > > > > > > > > > > Annovar DB configurations < < < < < < < < < < < < < < < < < < < < < < < < < <
DFLT_ANV_DB_DIR = os.environ['ANNOVAR_HUMAN_DB_DIR']
DFLT_ANV_DB_NAMES = "refGene"
DFLT_ANV_DB_OPS = "g"
DFLT_ANV_DB_NAMES += ",cytoBand"
DFLT_ANV_DB_OPS += ",r"
#DFLT_ANV_DB_NAMES += ",genomicSuperDups"
#DFLT_ANV_DB_OPS += ",r"
DFLT_ANV_DB_NAMES += ",exac03constraint"
DFLT_ANV_DB_OPS += ",r"
DFLT_ANV_DB_NAMES += ",1000g2014oct_eur"
DFLT_ANV_DB_OPS += ",f"
DFLT_ANV_DB_NAMES += ",1000g2014oct_all"
DFLT_ANV_DB_OPS += ",f"
DFLT_ANV_DB_NAMES += ",CMM_Swegen_20161223"
DFLT_ANV_DB_OPS += ",f"
DFLT_ANV_DB_NAMES += ",snp138"
DFLT_ANV_DB_OPS += ",f"
DFLT_ANV_DB_NAMES += ",exac03"
DFLT_ANV_DB_OPS += ",f"
DFLT_ANV_DB_NAMES += ",exac03nontcga"
DFLT_ANV_DB_OPS += ",f"
DFLT_ANV_DB_NAMES += ",gnomad_genome"
DFLT_ANV_DB_OPS += ",f"
#DFLT_ANV_DB_NAMES += ",cg69"
#DFLT_ANV_DB_OPS += ",f"
DFLT_ANV_DB_NAMES += ",cosmic70"
DFLT_ANV_DB_OPS += ",f"
#DFLT_ANV_DB_NAMES += ",nci60"
#DFLT_ANV_DB_OPS += ",f"
DFLT_ANV_DB_NAMES += ",spidex"
DFLT_ANV_DB_OPS += ",f"
DFLT_ANV_DB_NAMES += ",intervar"
DFLT_ANV_DB_OPS += ",f"
DFLT_ANV_DB_NAMES += ",clinvar_20150330"
DFLT_ANV_DB_OPS += ",f"
DFLT_ANV_DB_NAMES += ",clinvar_20170130"
DFLT_ANV_DB_OPS += ",f"
#DFLT_ANV_DB_NAMES += ",mitimpact2"
#DFLT_ANV_DB_OPS += ",f"
DFLT_ANV_DB_NAMES += ",CMM_OAF_BrC_CRC_prostate"
DFLT_ANV_DB_OPS += ",f"
DFLT_ANV_DB_NAMES += ",CMM_OAF_BrCs"
DFLT_ANV_DB_OPS += ",f"
DFLT_ANV_DB_NAMES += ",CMM_OAF_CRCs"
DFLT_ANV_DB_OPS += ",f"
DFLT_ANV_DB_NAMES += ",CMM_OAF_familial_CRCs"
DFLT_ANV_DB_OPS += ",f"
DFLT_ANV_DB_NAMES += ",CMM_OAF_CHEK2"
DFLT_ANV_DB_OPS += ",f"
DFLT_ANV_DB_NAMES += ",CMM_OAF_EARLYONSET"
DFLT_ANV_DB_OPS += ",f"
DFLT_ANV_DB_NAMES += ",CMM_OAF_familial_CRCs"
DFLT_ANV_DB_OPS += ",f"
DFLT_ANV_DB_NAMES += ",CMM_Axeq_chr3_6_14_18"
DFLT_ANV_DB_OPS += ",f"
DFLT_ANV_DB_NAMES += ",CMM_Axeq_chr5_19"
DFLT_ANV_DB_OPS += ",f"
DFLT_ANV_DB_NAMES += ",CMM_Axeq_chr9"
DFLT_ANV_DB_OPS += ",f"
DFLT_ANV_DB_NAMES += ",200_Danes"
DFLT_ANV_DB_OPS += ",f"
DFLT_ANV_DB_NAMES += ",249_Swedes"
DFLT_ANV_DB_OPS += ",f"
DFLT_ANV_DB_NAMES += ",ljb26_all"
DFLT_ANV_DB_OPS += ",f"

## > > > > > > > > > > > > > > > > > > > > > > > > > > Annotation columns < < < < < < < < < < < < < < < < < < < < < < < < < <
# This list will show all possible annotation columns (based on the dbs annotated by table_annovar.pl), in the INFO fields.
# Note. Defining CONSTANT var is for error detection purpose. It will raise exception if the constant is used without pre-defined value

# Columns group tags: Tags to define columns group. This is for exclusion purpose.
# Group of mitochondria-related columns
MT_COLS_TAG = "MT"
# Group of Axeq chr3, 6, 14, 18 columns
AXEQ_CHR3_6_14_18_COLS_TAG = "Axeq_chr3_6_14_18"
# Group of Axeq chr5, 19 columns
AXEQ_CHR5_19_COLS_TAG = "Axeq_chr5_19"
# Group of Axeq chr9 columns
AXEQ_CHR9_COLS_TAG = "Axeq_chr9"
# WES294_OAF_CRCs is a group of colorectal cancer samples, one famiy each, from a group of 294 exome sequencing samples
WES294_OAF_CRCS_COLS_TAG = "WES294_CRCS"
# WES294_OAF_BrCs is a group of breast cancer samples, one famiy each, from a group of 294 exome sequencing samples
WES294_OAF_BRC_COLS_TAG = "WES294_BRCS"
# WES294_BRC_CRC_PROSTATE is a group of all cancer samples, one famiy each, from a group of 294 exome sequencing samples
WES294_OAF_BRC_CRC_PROSTATE_COLS_TAG = "WES294_BRC_CRC_PROSTATE"
# WES294_OAF_CHEK2 is a group of CHEK2 samples, one famiy each, from a group of 294 exome sequencing samples
WES294_OAF_CHEK2_COLS_TAG = "WES294_CHEK2"
# WES294_OAF_EARLYONSET is a group early onset colorectal samples from a group of 294 exome sequencing samples
WES294_OAF_EARLYONSET_COLS_TAG = "WES294_EARLYONSET"
# WES294_OAF_CRCs is a group of familial colorectal cancer samples from a group of 294 exome sequencing samples
WES294_OAF_FAMILIAL_CRCS_COLS_TAG = "WES294_FAMILIAL_CRCS"
# Group of columns annotating detailed information of mutation stat
MUTSTAT_DETAILS_COLS_TAG = "Mutstat_details"
# Group of LJB score columns
LJB_SCORE_COLS_TAG = "LJB_score"
# Group of ExAC population frequencies beside ExAC_ALL and ExAC_NFE
EXAC_OTH_COLS_TAG = "ExAC_Other"
# Group of GNOMAD population frequencies beside ALL and NFE
GNOMAD_OTH_COLS_TAG = "GNOMAD_Other"
# Group of ExAC constraint indicating mutation intolerance for the gene
EXAC_CONSTRAINT_COLS_TAG = "ExAC_constraint"
# Group of other frequency-related from SWEGEN beside allele frequency
SWEGEN_OTH_COLS_TAG = "SWEGEN_Other"
# Group of KVOT calculation
KVOT_COLS_TAG = "KVOT"
# Group of columns that I don't really sure what it is about
UNKNOWN_COLS_TAG = "Unknown"

# Mitochondria-related columns
GENE_SYMBOL_COL_NAME = "Gene_symbol"
OXPHOS_COMPLEX_COL_NAME = "OXPHOS_Complex"
ENSEMBL_GENE_ID_COL_NAME = "Ensembl_Gene_ID"
ENSEMBL_PROTEIN_ID_COL_NAME = "Ensembl_Protein_ID"
UNIPROT_NAME_COL_NAME = "Uniprot_Name"
UNIPROT_ID_COL_NAME = "Uniprot_ID"
NCBI_GENE_ID_COL_NAME = "NCBI_Gene_ID"
NCBI_PROTEIN_ID_COL_NAME = "NCBI_Protein_ID"
GENE_POS_COL_NAME = "Gene_pos"
AA_POS_COL_NAME = "AA_pos"
AA_SUB_COL_NAME = "AA_sub"
CODON_SUB_COL_NAME = "Codon_sub"
DBSNP_ID_COL_NAME = "dbSNP_ID"
PHYLOP_46V_COL_NAME = "PhyloP_46V"
PHASTCONS_46V_COL_NAME = "PhastCons_46V"
PHYLOP_100V_COL_NAME = "PhyloP_100V"
PHASTCONS_100V_COL_NAME = "PhastCons_100V"
SITEVAR_COL_NAME = "SiteVar"
POLYPHEN2_PREDICTION_COL_NAME = "PolyPhen2_prediction"
POLYPHEN2_SCORE_COL_NAME = "PolyPhen2_score"
SIFT_PREDICTION_COL_NAME = "SIFT_prediction"
SIFT_SCORE_COL_NAME = "SIFT_score"
FATHMM_PREDICTION_COL_NAME = "FatHmm_prediction"
FATHMM_SCORE_COL_NAME = "FatHmm_score"
PROVEAN_PREDICTION_COL_NAME = "PROVEAN_prediction"
PROVEAN_SCORE_COL_NAME = "PROVEAN_score"
MUTASS_PREDICTION_COL_NAME = "MutAss_prediction"
MUTASS_SCORE_COL_NAME = "MutAss_score"
EFIN_SWISS_PROT_SCORE_COL_NAME = "EFIN_Swiss_Prot_Score"
EFIN_SWISS_PROT_PREDICTION_COL_NAME = "EFIN_Swiss_Prot_Prediction"
EFIN_HUMDIV_SCORE_COL_NAME = "EFIN_HumDiv_Score"
EFIN_HUMDIV_PREDICTION_COL_NAME = "EFIN_HumDiv_Prediction"
CADD_SCORE_COL_NAME = "CADD_score"
CADD_PHRED_SCORE_COL_NAME = "CADD_Phred_score"
CADD_PREDICTION_COL_NAME = "CADD_prediction"
CAROL_PREDICTION_COL_NAME = "Carol_prediction"
CAROL_SCORE_COL_NAME = "Carol_score"
CONDEL_SCORE_COL_NAME = "Condel_score"
CONDEL_PRED_COL_NAME = "Condel_pred"
COVEC_WMV_COL_NAME = "COVEC_WMV"
COVEC_WMV_PREDICTION_COL_NAME = "COVEC_WMV_prediction"
POLYPHEN2_SCORE_TRANSF_COL_NAME = "PolyPhen2_score_transf"
POLYPHEN2_PRED_TRANSF_COL_NAME = "PolyPhen2_pred_transf"
SIFT_SCORE_TRANSF_COL_NAME = "SIFT_score_transf"
SIFT_PRED_TRANSF_COL_NAME = "SIFT_pred_transf"
MUTASS_SCORE_TRANSF_COL_NAME = "MutAss_score_transf"
MUTASS_PRED_TRANSF_COL_NAME = "MutAss_pred_transf"
PERC_COEVO_SITES_COL_NAME = "Perc_coevo_Sites"
MEAN_MI_SCORE_COL_NAME = "Mean_MI_score"
COSMIC_ID_COL_NAME = "COSMIC_ID"
TUMOR_SITE_COL_NAME = "Tumor_site"
EXAMINED_SAMPLES_COL_NAME = "Examined_samples"
MUTATION_FREQUENCY_COL_NAME = "Mutation_frequency"
US_COL_NAME = "US"
STATUS_COL_NAME = "Status"
ASSOCIATED_DISEASE_COL_NAME = "Associated_disease"
PRESENCE_IN_TD_COL_NAME = "Presence_in_TD"
CLASS_PREDICTED_COL_NAME = "Class_predicted"
PROB_N_COL_NAME = "Prob_N"
PROB_P_COL_NAME = "Prob_P"

MT_ANNO_COLS = OrderedDict()
MT_ANNO_COLS[GENE_SYMBOL_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[OXPHOS_COMPLEX_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[ENSEMBL_GENE_ID_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[ENSEMBL_PROTEIN_ID_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[UNIPROT_NAME_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[UNIPROT_ID_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[NCBI_GENE_ID_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[NCBI_PROTEIN_ID_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[GENE_POS_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[AA_POS_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[AA_SUB_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[CODON_SUB_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[DBSNP_ID_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[PHYLOP_46V_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[PHASTCONS_46V_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[PHYLOP_100V_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[PHASTCONS_100V_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[SITEVAR_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[POLYPHEN2_PREDICTION_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[POLYPHEN2_SCORE_COL_NAME] = [MT_COLS_TAG]
#MT_ANNO_COLS[SIFT_PREDICTION_COL_NAME] = [MT_COLS_TAG]
#MT_ANNO_COLS[SIFT_SCORE_COL_NAME] = [MT_COLS_TAG]
#MT_ANNO_COLS[FATHMM_PREDICTION_COL_NAME] = [MT_COLS_TAG]
#MT_ANNO_COLS[FATHMM_SCORE_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[PROVEAN_PREDICTION_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[PROVEAN_SCORE_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[MUTASS_PREDICTION_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[MUTASS_SCORE_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[EFIN_SWISS_PROT_SCORE_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[EFIN_SWISS_PROT_PREDICTION_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[EFIN_HUMDIV_SCORE_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[EFIN_HUMDIV_PREDICTION_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[CADD_SCORE_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[CADD_PHRED_SCORE_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[CADD_PREDICTION_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[CAROL_PREDICTION_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[CAROL_SCORE_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[CONDEL_SCORE_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[CONDEL_PRED_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[COVEC_WMV_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[COVEC_WMV_PREDICTION_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[POLYPHEN2_SCORE_TRANSF_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[POLYPHEN2_PRED_TRANSF_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[SIFT_SCORE_TRANSF_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[SIFT_PRED_TRANSF_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[MUTASS_SCORE_TRANSF_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[MUTASS_PRED_TRANSF_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[PERC_COEVO_SITES_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[MEAN_MI_SCORE_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[COSMIC_ID_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[TUMOR_SITE_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[EXAMINED_SAMPLES_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[MUTATION_FREQUENCY_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[US_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[STATUS_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[ASSOCIATED_DISEASE_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[PRESENCE_IN_TD_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[CLASS_PREDICTED_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[PROB_N_COL_NAME] = [MT_COLS_TAG]
MT_ANNO_COLS[PROB_P_COL_NAME] = [MT_COLS_TAG]

# Effect predictor columns
LJB_SIFT_PREDICTION_COL_NAME = "SIFT_pred"
LJB_POLYPHEN2_HDIV_PREDICTION_COL_NAME = "Polyphen2_HDIV_pred"
LJB_POLYPHEN2_HVAR_PREDICTION_COL_NAME = "Polyphen2_HVAR_pred"
LJB_LRT_PREDICTION_COL_NAME = "LRT_pred"
LJB_MUTATIONTASTER_PREDICTION_COL_NAME = "MutationTaster_pred"
LJB_MUTATIONASSESSOR_PREDICTION_COL_NAME = "MutationAssessor_pred"
LJB_FATHMM_PREDICTION_COL_NAME = "FATHMM_pred"
LJB_RADIALSVM_PREDICTION_COL_NAME = "RadialSVM_pred"
LJB_LR_PREDICTION_COL_NAME = "LR_pred"
PATHOGENIC_COUNT_COL_NAME = "Pathogenic_count"

PREDICTION_COLS = {}
PREDICTION_COLS[LJB_SIFT_PREDICTION_COL_NAME] = []
PREDICTION_COLS[LJB_POLYPHEN2_HDIV_PREDICTION_COL_NAME] = []
PREDICTION_COLS[LJB_POLYPHEN2_HVAR_PREDICTION_COL_NAME] = []
PREDICTION_COLS[LJB_LRT_PREDICTION_COL_NAME] = []
PREDICTION_COLS[LJB_MUTATIONTASTER_PREDICTION_COL_NAME] = []
PREDICTION_COLS[LJB_MUTATIONASSESSOR_PREDICTION_COL_NAME] = []
PREDICTION_COLS[LJB_FATHMM_PREDICTION_COL_NAME] = []
PREDICTION_COLS[LJB_RADIALSVM_PREDICTION_COL_NAME] = []
PREDICTION_COLS[LJB_LR_PREDICTION_COL_NAME] = []

# Other columns
FUNC_REFGENE_COL_NAME = "Func.refGene"
EXONICFUNC_REFGENE_COL_NAME = "ExonicFunc.refGene"
GENE_REFGENE_COL_NAME = "Gene.refGene"
GENEDETAIL_REFGENE_COL_NAME = "GeneDetail.refGene"
SNP138_COL_NAME = "snp138"
MAX_REF_MAF_COL_NAME = "MAX_REF_MAF"
KG2014OCT_EUR_COL_NAME = "1000g2014oct_eur"
KG2014OCT_ALL_COL_NAME = "1000g2014oct_all"
AXEQ_CHR3_6_14_18_PF_COL_NAME = "AXEQ_CHR3_6_14_18_PF"
AXEQ_CHR3_6_14_18_GF_COL_NAME = "AXEQ_CHR3_6_14_18_GF"
AXEQ_CHR5_19_PF_COL_NAME = "AXEQ_CHR5_19_PF"
AXEQ_CHR5_19_GF_COL_NAME = "AXEQ_CHR5_19_GF"
AXEQ_CHR9_PF_COL_NAME = "AXEQ_CHR9_PF"
AXEQ_CHR9_GF_COL_NAME = "AXEQ_CHR9_GF"
SWEDES_COL_NAME = "249_SWEDES"
DANES_COL_NAME = "200_DANES"
SWEGEN_HET_COL_NAME = "SWEGEN_HET"
SWEGEN_HOM_COL_NAME = "SWEGEN_HOM"
SWEGEN_HEMI_COL_NAME = "SWEGEN_HEMI"
SWEGEN_AC_COL_NAME = "SWEGEN_AC"
SWEGEN_GT_COL_NAME = "SWEGEN_GT"
SWEGEN_GF_COL_NAME = "SWEGEN_GF"
SWEGEN_AF_COL_NAME = "SWEGEN_AF"
SWEGEN_PF_COL_NAME = "SWEGEN_PF"
EXAC_ALL_COL_NAME = "ExAC_ALL"
EXAC_AFR_COL_NAME = "ExAC_AFR"
EXAC_AMR_COL_NAME = "ExAC_AMR"
EXAC_EAS_COL_NAME = "ExAC_EAS"
EXAC_FIN_COL_NAME = "ExAC_FIN"
EXAC_NFE_COL_NAME = "ExAC_NFE"
EXAC_OTH_COL_NAME = "ExAC_OTH"
EXAC_SAS_COL_NAME = "ExAC_SAS"
EXAC_NONTCGA_ALL_COL_NAME = "ExAC_nontcga_ALL"
EXAC_NONTCGA_AFR_COL_NAME = "ExAC_nontcga_AFR"
EXAC_NONTCGA_AMR_COL_NAME = "ExAC_nontcga_AMR"
EXAC_NONTCGA_EAS_COL_NAME = "ExAC_nontcga_EAS"
EXAC_NONTCGA_FIN_COL_NAME = "ExAC_nontcga_FIN"
EXAC_NONTCGA_NFE_COL_NAME = "ExAC_nontcga_NFE"
EXAC_NONTCGA_OTH_COL_NAME = "ExAC_nontcga_OTH"
EXAC_NONTCGA_SAS_COL_NAME = "ExAC_nontcga_SAS"
EXAC03_CONSTRAINT_COL_NAME = 'exac03constraint'
GNOMAD_GENOME_ALL_COL_NAME = "gnomAD_genome_ALL"
GNOMAD_GENOME_AFR_COL_NAME = "gnomAD_genome_AFR"
GNOMAD_GENOME_AMR_COL_NAME = "gnomAD_genome_AMR"
GNOMAD_GENOME_ASJ_COL_NAME = "gnomAD_genome_ASJ"
GNOMAD_GENOME_EAS_COL_NAME = "gnomAD_genome_EAS"
GNOMAD_GENOME_FIN_COL_NAME = "gnomAD_genome_FIN"
GNOMAD_GENOME_NFE_COL_NAME = "gnomAD_genome_NFE"
GNOMAD_GENOME_OTH_COL_NAME = "gnomAD_genome_OTH"
EXAC03_CONSTRAINT_EXP_SYN_COL_NAME = "EXAC03_CONSTRAINT_EXP_SYN"
EXAC03_CONSTRAINT_N_SYN_COL_NAME = "EXAC03_CONSTRAINT_N_SYN"
EXAC03_CONSTRAINT_SYN_Z_COL_NAME = "EXAC03_CONSTRAINT_SYN_Z"
EXAC03_CONSTRAINT_EXP_MIS_COL_NAME = "EXAC03_CONSTRAINT_EXP_MIS"
EXAC03_CONSTRAINT_N_MIS_COL_NAME = "EXAC03_CONSTRAINT_N_MIS"
EXAC03_CONSTRAINT_MIS_Z_COL_NAME = "EXAC03_CONSTRAINT_MIS_Z"
EXAC03_CONSTRAINT_EXP_LOF_COL_NAME = "EXAC03_CONSTRAINT_EXP_LOF"
EXAC03_CONSTRAINT_N_LOF_COL_NAME = "EXAC03_CONSTRAINT_N_LOF"
EXAC03_CONSTRAINT_PLI_COL_NAME = "EXAC03_CONSTRAINT_PLI"
AACHANGE_REFGENE_COL_NAME = "AAChange.refGene"
CYTOBAND_COL_NAME = "cytoBand"
#GENOMICSUPERDUPS_COL_NAME = "genomicSuperDups"
#CG69_COL_NAME = "cg69"
COSMIC70_COL_NAME = "cosmic70"
#NCI60_COL_NAME = "nci60"
CLINSIG_COL_NAME = "CLINSIG"
CLNDBN_COL_NAME = "CLNDBN"
CLNACC_COL_NAME = "CLNACC"
CLNDSDB_COL_NAME = "CLNDSDB"
CLNDSDBID_COL_NAME = "CLNDSDBID"
CLINVAR_20150330_COL_NAME = "clinvar_20150330"
WES294_OAF_BRCS_WT_COL_NAME = "OAF_BRCS_WT"
WES294_OAF_BRCS_HET_COL_NAME = "OAF_BRCS_HET"
WES294_OAF_BRCS_HOM_COL_NAME = "OAF_BRCS_HOM"
WES294_OAF_BRCS_OTH_COL_NAME = "OAF_BRCS_OTH"
WES294_OAF_BRCS_NA_COL_NAME = "OAF_BRCS_NA"
WES294_OAF_BRCS_GT_COL_NAME = "OAF_BRCS_GT"
WES294_OAF_BRCS_PF_COL_NAME = "OAF_BRCS_PF"
WES294_OAF_BRCS_AF_COL_NAME = "OAF_BRCS_AF"
WES294_OAF_BRCS_GF_COL_NAME = "OAF_BRCS_GF"
WES294_OAF_CRCS_WT_COL_NAME = "OAF_CRCS_WT"
WES294_OAF_CRCS_HET_COL_NAME = "OAF_CRCS_HET"
WES294_OAF_CRCS_HOM_COL_NAME = "OAF_CRCS_HOM"
WES294_OAF_CRCS_OTH_COL_NAME = "OAF_CRCS_OTH"
WES294_OAF_CRCS_NA_COL_NAME = "OAF_CRCS_NA"
WES294_OAF_CRCS_GT_COL_NAME = "OAF_CRCS_GT"
WES294_OAF_CRCS_PF_COL_NAME = "OAF_CRCS_PF"
WES294_OAF_CRCS_AF_COL_NAME = "OAF_CRCS_AF"
WES294_OAF_CRCS_GF_COL_NAME = "OAF_CRCS_GF"
WES294_OAF_BRC_CRC_PROSTATE_WT_COL_NAME = "OAF_BRC_CRC_PROSTATE_WT"
WES294_OAF_BRC_CRC_PROSTATE_HET_COL_NAME = "OAF_BRC_CRC_PROSTATE_HET"
WES294_OAF_BRC_CRC_PROSTATE_HOM_COL_NAME = "OAF_BRC_CRC_PROSTATE_HOM"
WES294_OAF_BRC_CRC_PROSTATE_OTH_COL_NAME = "OAF_BRC_CRC_PROSTATE_OTH"
WES294_OAF_BRC_CRC_PROSTATE_NA_COL_NAME = "OAF_BRC_CRC_PROSTATE_NA"
WES294_OAF_BRC_CRC_PROSTATE_GT_COL_NAME = "OAF_BRC_CRC_PROSTATE_GT"
WES294_OAF_BRC_CRC_PROSTATE_PF_COL_NAME = "OAF_BRC_CRC_PROSTATE_PF"
WES294_OAF_BRC_CRC_PROSTATE_AF_COL_NAME = "OAF_BRC_CRC_PROSTATE_AF"
WES294_OAF_BRC_CRC_PROSTATE_GF_COL_NAME = "OAF_BRC_CRC_PROSTATE_GF"
WES294_OAF_CHEK2_WT_COL_NAME = "OAF_CHEK2_WT"
WES294_OAF_CHEK2_HET_COL_NAME = "OAF_CHEK2_HET"
WES294_OAF_CHEK2_HOM_COL_NAME = "OAF_CHEK2_HOM"
WES294_OAF_CHEK2_OTH_COL_NAME = "OAF_CHEK2_OTH"
WES294_OAF_CHEK2_NA_COL_NAME = "OAF_CHEK2_NA"
WES294_OAF_CHEK2_GT_COL_NAME = "OAF_CHEK2_GT"
WES294_OAF_CHEK2_PF_COL_NAME = "OAF_CHEK2_PF"
WES294_OAF_CHEK2_AF_COL_NAME = "OAF_CHEK2_AF"
WES294_OAF_CHEK2_GF_COL_NAME = "OAF_CHEK2_GF"
WES294_OAF_EARLYONSET_WT_COL_NAME = "OAF_EARLYONSET_WT"
WES294_OAF_EARLYONSET_HET_COL_NAME = "OAF_EARLYONSET_HET"
WES294_OAF_EARLYONSET_HOM_COL_NAME = "OAF_EARLYONSET_HOM"
WES294_OAF_EARLYONSET_OTH_COL_NAME = "OAF_EARLYONSET_OTH"
WES294_OAF_EARLYONSET_NA_COL_NAME = "OAF_EARLYONSET_NA"
WES294_OAF_EARLYONSET_GT_COL_NAME = "OAF_EARLYONSET_GT"
WES294_OAF_EARLYONSET_PF_COL_NAME = "OAF_EARLYONSET_PF"
WES294_OAF_FAMILIAL_CRCS_WT_COL_NAME = "OAF_FAMILIAL_CRCS_WT"
WES294_OAF_FAMILIAL_CRCS_HET_COL_NAME = "OAF_FAMILIAL_CRCS_HET"
WES294_OAF_FAMILIAL_CRCS_HOM_COL_NAME = "OAF_FAMILIAL_CRCS_HOM"
WES294_OAF_FAMILIAL_CRCS_OTH_COL_NAME = "OAF_FAMILIAL_CRCS_OTH"
WES294_OAF_FAMILIAL_CRCS_NA_COL_NAME = "OAF_FAMILIAL_CRCS_NA"
WES294_OAF_FAMILIAL_CRCS_GT_COL_NAME = "OAF_FAMILIAL_CRCS_GT"
WES294_OAF_FAMILIAL_CRCS_PF_COL_NAME = "OAF_FAMILIAL_CRCS_PF"
WES294_OAF_FAMILIAL_CRCS_AF_COL_NAME = "OAF_FAMILIAL_CRCS_AF"
WES294_OAF_FAMILIAL_CRCS_GF_COL_NAME = "OAF_FAMILIAL_CRCS_GF"
EST_KVOT_EARLYONSET_VS_BRC_COL_NAME = "KVOT_EARLYONSET_VS_BRC_ESTIMATED"
EST_KVOT_EARLYONSET_VS_EXAC_NFE_COL_NAME = "KVOT_EARLYONSET_VS_EXAC_NFE_ESTIMATED"
EST_KVOT_EARLYONSET_VS_KG_EUR_COL_NAME = "KVOT_EARLYONSET_VS_1000G_EUR_ESTIMATED"
EST_KVOT_EARLYONSET_VS_SWEGEN_COL_NAME = "KVOT_EARLYONSET_VS_SWEGEN_ESTIMATED"
WES294_OAF_EARLYONSET_AF_COL_NAME = "OAF_EARLYONSET_AF"
WES294_OAF_EARLYONSET_GF_COL_NAME = "OAF_EARLYONSET_GF"
AXEQ_CHR3_6_14_18_WT_COL_NAME = "AXEQ_CHR3_6_14_18_WT"
AXEQ_CHR3_6_14_18_HET_COL_NAME = "AXEQ_CHR3_6_14_18_HET"
AXEQ_CHR3_6_14_18_HOM_COL_NAME = "AXEQ_CHR3_6_14_18_HOM"
AXEQ_CHR3_6_14_18_OTH_COL_NAME = "AXEQ_CHR3_6_14_18_OTH"
AXEQ_CHR3_6_14_18_NA_COL_NAME = "AXEQ_CHR3_6_14_18_NA"
AXEQ_CHR3_6_14_18_GT_COL_NAME = "AXEQ_CHR3_6_14_18_GT"
AXEQ_CHR3_6_14_18_AF_COL_NAME = "AXEQ_CHR3_6_14_18_AF"
AXEQ_CHR5_19_WT_COL_NAME = "AXEQ_CHR5_19_WT"
AXEQ_CHR5_19_HET_COL_NAME = "AXEQ_CHR5_19_HET"
AXEQ_CHR5_19_HOM_COL_NAME = "AXEQ_CHR5_19_HOM"
AXEQ_CHR5_19_OTH_COL_NAME = "AXEQ_CHR5_19_OTH"
AXEQ_CHR5_19_NA_COL_NAME = "AXEQ_CHR5_19_NA"
AXEQ_CHR5_19_GT_COL_NAME = "AXEQ_CHR5_19_GT"
AXEQ_CHR5_19_AF_COL_NAME = "AXEQ_CHR5_19_AF"
AXEQ_CHR9_WT_COL_NAME = "AXEQ_CHR9_WT"
AXEQ_CHR9_HET_COL_NAME = "AXEQ_CHR9_HET"
AXEQ_CHR9_HOM_COL_NAME = "AXEQ_CHR9_HOM"
AXEQ_CHR9_OTH_COL_NAME = "AXEQ_CHR9_OTH"
AXEQ_CHR9_NA_COL_NAME = "AXEQ_CHR9_NA"
AXEQ_CHR9_GT_COL_NAME = "AXEQ_CHR9_GT"
AXEQ_CHR9_AF_COL_NAME = "AXEQ_CHR9_AF"
SPIDEX_DPSI_MAX_TISSUE_COL_NAME = "dpsi_max_tissue"
SPIDEX_DPSI_ZSCORE_COL_NAME = "dpsi_zscore"
INTERVAR_AND_EVIDENCE_COL_NAME = "InterVar:InterVarAndEvidence"
INTERVAR_CLASS_COL_NAME = "InterVar_class"
INTERVAR_EVIDENCE_COL_NAME = "InterVar_evidence"
SIFT_SCORE_COL_NAME = "SIFT_score"
POLYPHEN2_HDIV_SCORE_COL_NAME = "Polyphen2_HDIV_score"
POLYPHEN2_HVAR_SCORE_COL_NAME = "Polyphen2_HVAR_score"
LRT_SCORE_COL_NAME = "LRT_score"
MUTATIONTASTER_SCORE_COL_NAME = "MutationTaster_score"
MUTATIONASSESSOR_SCORE_COL_NAME = "MutationAssessor_score"
FATHMM_SCORE_COL_NAME = "FATHMM_score"
RADIALSVM_SCORE_COL_NAME = "RadialSVM_score"
LR_SCORE_COL_NAME = "LR_score"
VEST3_SCORE_COL_NAME = "VEST3_score"
CADD_RAW_COL_NAME = "CADD_raw"
CADD_PHRED_COL_NAME = "CADD_phred"
GERP_RS_COL_NAME = "GERP++_RS"
PHYLOP46WAY_PLACENTAL_COL_NAME = "phyloP46way_placental"
PHYLOP100WAY_VERTEBRATE_COL_NAME = "phyloP100way_vertebrate"
SIPHY_29WAY_LOGODDS_COL_NAME = "SiPhy_29way_logOdds"
COMPOUND_HETEROZYGOTE_AFFECTED_COUNT_COL_NAME = "compound_heterozygote_affected_count"
COMPOUND_HETEROZYGOTE_UNAFFECTED_COUNT_COL_NAME = "compound_heterozygote_unaffected_count"
COMPOUND_HETEROZYGOTE_FREQ_RATIO_COL_NAME = "compound_heterozygote_frequency_ratio"
HOMOZYGOTE_AFFECTED_COUNT_COL_NAME = "homozygote_affected_count"
HOMOZYGOTE_UNAFFECTED_COUNT_COL_NAME = "homozygote_unaffected_count"
HOMOZYGOTE_FREQ_RATIO_COL_NAME = "homozygote_frequency_ratio"

RECESSIVE_STUDY_COL_NAMES = []
RECESSIVE_STUDY_COL_NAMES.append(COMPOUND_HETEROZYGOTE_AFFECTED_COUNT_COL_NAME)
RECESSIVE_STUDY_COL_NAMES.append(COMPOUND_HETEROZYGOTE_UNAFFECTED_COUNT_COL_NAME)
RECESSIVE_STUDY_COL_NAMES.append(COMPOUND_HETEROZYGOTE_FREQ_RATIO_COL_NAME)
RECESSIVE_STUDY_COL_NAMES.append(HOMOZYGOTE_AFFECTED_COUNT_COL_NAME)
RECESSIVE_STUDY_COL_NAMES.append(HOMOZYGOTE_UNAFFECTED_COUNT_COL_NAME)
RECESSIVE_STUDY_COL_NAMES.append(HOMOZYGOTE_FREQ_RATIO_COL_NAME)

PRIMARY_MAF_VAR = KG2014OCT_EUR_COL_NAME
DFLT_MUTREP_FREQ_RATIOS = PRIMARY_MAF_VAR + ":0.2"
FUNC_REFGENE_VAR = FUNC_REFGENE_COL_NAME
EXONICFUNC_REFGENE_VAR = EXONICFUNC_REFGENE_COL_NAME

REF_MAF_COL_NAMES = {}
REF_MAF_COL_NAMES[SWEGEN_AF_COL_NAME] = []
REF_MAF_COL_NAMES[EXAC_NFE_COL_NAME] = []
REF_MAF_COL_NAMES[EXAC_ALL_COL_NAME] = []
REF_MAF_COL_NAMES[EXAC_AFR_COL_NAME] = []
REF_MAF_COL_NAMES[EXAC_AMR_COL_NAME] = []
REF_MAF_COL_NAMES[EXAC_EAS_COL_NAME] = []
REF_MAF_COL_NAMES[EXAC_FIN_COL_NAME] = []
REF_MAF_COL_NAMES[EXAC_OTH_COL_NAME] = []
REF_MAF_COL_NAMES[EXAC_SAS_COL_NAME] = []
REF_MAF_COL_NAMES[KG2014OCT_EUR_COL_NAME] = []
REF_MAF_COL_NAMES[KG2014OCT_ALL_COL_NAME] = []
REF_MAF_COL_NAMES[SWEDES_COL_NAME] = []
REF_MAF_COL_NAMES[DANES_COL_NAME] = []
REF_MAF_COL_NAMES[GNOMAD_GENOME_ALL_COL_NAME] = []
REF_MAF_COL_NAMES[GNOMAD_GENOME_AFR_COL_NAME] = []
REF_MAF_COL_NAMES[GNOMAD_GENOME_AMR_COL_NAME] = []
REF_MAF_COL_NAMES[GNOMAD_GENOME_ASJ_COL_NAME] = []
REF_MAF_COL_NAMES[GNOMAD_GENOME_EAS_COL_NAME] = []
REF_MAF_COL_NAMES[GNOMAD_GENOME_FIN_COL_NAME] = []
REF_MAF_COL_NAMES[GNOMAD_GENOME_NFE_COL_NAME] = []
REF_MAF_COL_NAMES[GNOMAD_GENOME_OTH_COL_NAME] = []

# defining all annotation columns
# manually assigning is because not all columns have their own tags
# This is the place to define columns order
ALL_MUTREP_ANNO_COLS = OrderedDict()
ALL_MUTREP_ANNO_COLS[FUNC_REFGENE_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[EXONICFUNC_REFGENE_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[SNP138_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[GENE_REFGENE_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[GENEDETAIL_REFGENE_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AACHANGE_REFGENE_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CYTOBAND_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[MAX_REF_MAF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[EST_KVOT_EARLYONSET_VS_SWEGEN_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[SWEGEN_AF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[SWEGEN_GF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[EST_KVOT_EARLYONSET_VS_EXAC_NFE_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[EXAC_NFE_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[EXAC_ALL_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[EXAC_NONTCGA_NFE_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[EXAC_NONTCGA_ALL_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[EST_KVOT_EARLYONSET_VS_KG_EUR_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[KG2014OCT_EUR_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[KG2014OCT_ALL_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_EARLYONSET_AF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_EARLYONSET_GF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[EST_KVOT_EARLYONSET_VS_BRC_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[GNOMAD_GENOME_ALL_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[GNOMAD_GENOME_NFE_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_BRCS_AF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_BRCS_GF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_CRCS_AF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_CRCS_GF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_FAMILIAL_CRCS_AF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_FAMILIAL_CRCS_GF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_BRC_CRC_PROSTATE_AF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_BRC_CRC_PROSTATE_GF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_CHEK2_AF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_CHEK2_GF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR3_6_14_18_AF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR3_6_14_18_GF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR5_19_AF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR5_19_GF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR9_AF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR9_GF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[SWEDES_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[DANES_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[SWEGEN_HET_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[SWEGEN_HOM_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[SWEGEN_HEMI_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[SWEGEN_AC_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[SWEGEN_GT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[SWEGEN_PF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[EXAC_AFR_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[EXAC_AMR_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[EXAC_EAS_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[EXAC_FIN_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[EXAC_OTH_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[EXAC_SAS_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[EXAC_NONTCGA_AFR_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[EXAC_NONTCGA_AMR_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[EXAC_NONTCGA_EAS_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[EXAC_NONTCGA_FIN_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[EXAC_NONTCGA_OTH_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[EXAC_NONTCGA_SAS_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[GNOMAD_GENOME_AFR_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[GNOMAD_GENOME_AMR_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[GNOMAD_GENOME_ASJ_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[GNOMAD_GENOME_EAS_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[GNOMAD_GENOME_FIN_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[GNOMAD_GENOME_OTH_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[EXAC03_CONSTRAINT_EXP_SYN_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[EXAC03_CONSTRAINT_N_SYN_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[EXAC03_CONSTRAINT_SYN_Z_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[EXAC03_CONSTRAINT_EXP_MIS_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[EXAC03_CONSTRAINT_N_MIS_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[EXAC03_CONSTRAINT_MIS_Z_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[EXAC03_CONSTRAINT_EXP_LOF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[EXAC03_CONSTRAINT_N_LOF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[EXAC03_CONSTRAINT_PLI_COL_NAME] = []
#ALL_MUTREP_ANNO_COLS[GENOMICSUPERDUPS_COL_NAME] = []
#ALL_MUTREP_ANNO_COLS[CG69_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[COSMIC70_COL_NAME] = []
#ALL_MUTREP_ANNO_COLS[NCI60_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CLINVAR_20150330_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CLINSIG_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CLNDBN_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CLNACC_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CLNDSDB_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CLNDSDBID_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[SPIDEX_DPSI_MAX_TISSUE_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[SPIDEX_DPSI_ZSCORE_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[INTERVAR_CLASS_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[INTERVAR_EVIDENCE_COL_NAME] = []

#ALL_MUTREP_ANNO_COLS.update(MT_ANNO_COLS)

ALL_MUTREP_ANNO_COLS[AXEQ_CHR3_6_14_18_WT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR3_6_14_18_HET_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR3_6_14_18_HOM_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR3_6_14_18_OTH_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR3_6_14_18_NA_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR3_6_14_18_GT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR3_6_14_18_PF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR5_19_WT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR5_19_HET_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR5_19_HOM_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR5_19_OTH_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR5_19_NA_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR5_19_GT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR5_19_PF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR9_WT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR9_HET_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR9_HOM_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR9_OTH_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR9_NA_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR9_GT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[AXEQ_CHR9_PF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_CRCS_HET_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_CRCS_HOM_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_CRCS_OTH_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_CRCS_NA_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_CRCS_GT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_CRCS_PF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_CRCS_WT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_BRCS_WT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_BRCS_HET_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_BRCS_HOM_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_BRCS_OTH_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_BRCS_NA_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_BRCS_GT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_BRCS_PF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_BRC_CRC_PROSTATE_WT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_BRC_CRC_PROSTATE_HET_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_BRC_CRC_PROSTATE_HOM_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_BRC_CRC_PROSTATE_OTH_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_BRC_CRC_PROSTATE_NA_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_BRC_CRC_PROSTATE_GT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_BRC_CRC_PROSTATE_PF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_CHEK2_WT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_CHEK2_HET_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_CHEK2_HOM_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_CHEK2_OTH_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_CHEK2_NA_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_CHEK2_GT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_CHEK2_PF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_EARLYONSET_WT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_EARLYONSET_HET_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_EARLYONSET_HOM_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_EARLYONSET_OTH_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_EARLYONSET_NA_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_EARLYONSET_GT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_EARLYONSET_PF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_FAMILIAL_CRCS_HET_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_FAMILIAL_CRCS_HOM_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_FAMILIAL_CRCS_OTH_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_FAMILIAL_CRCS_NA_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_FAMILIAL_CRCS_GT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_FAMILIAL_CRCS_PF_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[WES294_OAF_FAMILIAL_CRCS_WT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[PATHOGENIC_COUNT_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[SIFT_SCORE_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[LJB_SIFT_PREDICTION_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[POLYPHEN2_HDIV_SCORE_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[LJB_POLYPHEN2_HDIV_PREDICTION_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[POLYPHEN2_HVAR_SCORE_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[LJB_POLYPHEN2_HVAR_PREDICTION_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[LRT_SCORE_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[LJB_LRT_PREDICTION_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[MUTATIONTASTER_SCORE_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[LJB_MUTATIONTASTER_PREDICTION_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[MUTATIONASSESSOR_SCORE_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[LJB_MUTATIONASSESSOR_PREDICTION_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[FATHMM_SCORE_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[LJB_FATHMM_PREDICTION_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[RADIALSVM_SCORE_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[LJB_RADIALSVM_PREDICTION_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[LR_SCORE_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[LJB_LR_PREDICTION_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[VEST3_SCORE_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CADD_RAW_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[CADD_PHRED_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[GERP_RS_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[PHYLOP46WAY_PLACENTAL_COL_NAME] = []
ALL_MUTREP_ANNO_COLS[PHYLOP100WAY_VERTEBRATE_COL_NAME] = []

FORMAT_COL_FLOAT = "fmt_float"
FORMAT_COL_INT = "fmt_int"
FORMAT_COLS = {}
FORMAT_COLS[SPIDEX_DPSI_MAX_TISSUE_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[SPIDEX_DPSI_ZSCORE_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[EXAC03_CONSTRAINT_EXP_SYN_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[EXAC03_CONSTRAINT_N_SYN_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[EXAC03_CONSTRAINT_SYN_Z_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[EXAC03_CONSTRAINT_EXP_MIS_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[EXAC03_CONSTRAINT_N_MIS_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[EXAC03_CONSTRAINT_MIS_Z_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[EXAC03_CONSTRAINT_EXP_LOF_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[EXAC03_CONSTRAINT_N_LOF_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[EXAC03_CONSTRAINT_PLI_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[WES294_OAF_BRCS_WT_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[WES294_OAF_BRCS_HET_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[WES294_OAF_BRCS_HOM_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[WES294_OAF_BRCS_OTH_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[WES294_OAF_BRCS_NA_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[WES294_OAF_BRCS_GT_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[WES294_OAF_BRCS_PF_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[WES294_OAF_BRCS_AF_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[WES294_OAF_BRCS_GF_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[WES294_OAF_CRCS_WT_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[WES294_OAF_CRCS_HET_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[WES294_OAF_CRCS_HOM_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[WES294_OAF_CRCS_OTH_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[WES294_OAF_CRCS_NA_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[WES294_OAF_CRCS_GT_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[WES294_OAF_CRCS_PF_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[WES294_OAF_CRCS_AF_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[WES294_OAF_CRCS_GF_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[WES294_OAF_BRC_CRC_PROSTATE_WT_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[WES294_OAF_BRC_CRC_PROSTATE_HET_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[WES294_OAF_BRC_CRC_PROSTATE_HOM_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[WES294_OAF_BRC_CRC_PROSTATE_OTH_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[WES294_OAF_BRC_CRC_PROSTATE_NA_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[WES294_OAF_BRC_CRC_PROSTATE_GT_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[WES294_OAF_BRC_CRC_PROSTATE_PF_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[WES294_OAF_BRC_CRC_PROSTATE_AF_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[WES294_OAF_BRC_CRC_PROSTATE_GF_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[WES294_OAF_CHEK2_WT_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[WES294_OAF_CHEK2_HET_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[WES294_OAF_CHEK2_HOM_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[WES294_OAF_CHEK2_OTH_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[WES294_OAF_CHEK2_NA_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[WES294_OAF_CHEK2_GT_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[WES294_OAF_CHEK2_PF_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[WES294_OAF_CHEK2_AF_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[WES294_OAF_CHEK2_GF_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[WES294_OAF_EARLYONSET_WT_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[WES294_OAF_EARLYONSET_HET_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[WES294_OAF_EARLYONSET_HOM_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[WES294_OAF_EARLYONSET_OTH_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[WES294_OAF_EARLYONSET_NA_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[WES294_OAF_EARLYONSET_GT_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[WES294_OAF_EARLYONSET_PF_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[WES294_OAF_EARLYONSET_AF_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[WES294_OAF_EARLYONSET_GF_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[WES294_OAF_FAMILIAL_CRCS_WT_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[WES294_OAF_FAMILIAL_CRCS_HET_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[WES294_OAF_FAMILIAL_CRCS_HOM_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[WES294_OAF_FAMILIAL_CRCS_OTH_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[WES294_OAF_FAMILIAL_CRCS_NA_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[WES294_OAF_FAMILIAL_CRCS_GT_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[WES294_OAF_FAMILIAL_CRCS_PF_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[WES294_OAF_FAMILIAL_CRCS_AF_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[WES294_OAF_FAMILIAL_CRCS_GF_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[EST_KVOT_EARLYONSET_VS_BRC_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[EST_KVOT_EARLYONSET_VS_EXAC_NFE_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[EST_KVOT_EARLYONSET_VS_SWEGEN_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[EST_KVOT_EARLYONSET_VS_KG_EUR_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[AXEQ_CHR3_6_14_18_WT_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[AXEQ_CHR3_6_14_18_HET_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[AXEQ_CHR3_6_14_18_HOM_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[AXEQ_CHR3_6_14_18_OTH_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[AXEQ_CHR3_6_14_18_NA_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[AXEQ_CHR3_6_14_18_GT_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[AXEQ_CHR3_6_14_18_AF_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[AXEQ_CHR3_6_14_18_PF_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[AXEQ_CHR3_6_14_18_GF_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[AXEQ_CHR5_19_WT_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[AXEQ_CHR5_19_HET_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[AXEQ_CHR5_19_HOM_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[AXEQ_CHR5_19_OTH_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[AXEQ_CHR5_19_NA_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[AXEQ_CHR5_19_GT_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[AXEQ_CHR5_19_AF_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[AXEQ_CHR5_19_PF_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[AXEQ_CHR5_19_GF_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[AXEQ_CHR9_WT_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[AXEQ_CHR9_HET_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[AXEQ_CHR9_HOM_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[AXEQ_CHR9_OTH_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[AXEQ_CHR9_NA_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[AXEQ_CHR9_GT_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[AXEQ_CHR9_AF_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[AXEQ_CHR9_PF_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[AXEQ_CHR9_GF_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[SWEDES_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[DANES_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[SWEGEN_HET_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[SWEGEN_HOM_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[SWEGEN_HEMI_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[SWEGEN_AC_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[SWEGEN_GT_COL_NAME] = FORMAT_COL_INT
FORMAT_COLS[SWEGEN_GF_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[SWEGEN_AF_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[SWEGEN_PF_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[EXAC_ALL_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[EXAC_AFR_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[EXAC_AMR_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[EXAC_EAS_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[EXAC_FIN_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[EXAC_NFE_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[EXAC_OTH_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[EXAC_SAS_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[CADD_RAW_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[SIFT_SCORE_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[POLYPHEN2_HDIV_SCORE_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[POLYPHEN2_HVAR_SCORE_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[LRT_SCORE_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[MUTATIONTASTER_SCORE_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[MUTATIONASSESSOR_SCORE_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[FATHMM_SCORE_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[RADIALSVM_SCORE_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[LR_SCORE_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[VEST3_SCORE_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[CADD_PHRED_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[GERP_RS_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[PHYLOP46WAY_PLACENTAL_COL_NAME] = FORMAT_COL_FLOAT
FORMAT_COLS[PHYLOP100WAY_VERTEBRATE_COL_NAME] = FORMAT_COL_FLOAT

# set tags
cols_tags = {}
# set columns associated with AXEQ_CHR3_6_14_18_COLS_TAG
cols_tags[AXEQ_CHR3_6_14_18_COLS_TAG] = []
cols_tags[AXEQ_CHR3_6_14_18_COLS_TAG].append(AXEQ_CHR3_6_14_18_WT_COL_NAME)
cols_tags[AXEQ_CHR3_6_14_18_COLS_TAG].append(AXEQ_CHR3_6_14_18_HET_COL_NAME)
cols_tags[AXEQ_CHR3_6_14_18_COLS_TAG].append(AXEQ_CHR3_6_14_18_HOM_COL_NAME)
cols_tags[AXEQ_CHR3_6_14_18_COLS_TAG].append(AXEQ_CHR3_6_14_18_OTH_COL_NAME)
cols_tags[AXEQ_CHR3_6_14_18_COLS_TAG].append(AXEQ_CHR3_6_14_18_NA_COL_NAME)
cols_tags[AXEQ_CHR3_6_14_18_COLS_TAG].append(AXEQ_CHR3_6_14_18_GT_COL_NAME)
cols_tags[AXEQ_CHR3_6_14_18_COLS_TAG].append(AXEQ_CHR3_6_14_18_AF_COL_NAME)
cols_tags[AXEQ_CHR3_6_14_18_COLS_TAG].append(AXEQ_CHR3_6_14_18_PF_COL_NAME)
cols_tags[AXEQ_CHR3_6_14_18_COLS_TAG].append(AXEQ_CHR3_6_14_18_GF_COL_NAME)

# set columns associated with AXEQ_CHR5_19_COLS_TAG
cols_tags[AXEQ_CHR5_19_COLS_TAG] = []
cols_tags[AXEQ_CHR5_19_COLS_TAG].append(AXEQ_CHR5_19_WT_COL_NAME)
cols_tags[AXEQ_CHR5_19_COLS_TAG].append(AXEQ_CHR5_19_HET_COL_NAME)
cols_tags[AXEQ_CHR5_19_COLS_TAG].append(AXEQ_CHR5_19_HOM_COL_NAME)
cols_tags[AXEQ_CHR5_19_COLS_TAG].append(AXEQ_CHR5_19_OTH_COL_NAME)
cols_tags[AXEQ_CHR5_19_COLS_TAG].append(AXEQ_CHR5_19_NA_COL_NAME)
cols_tags[AXEQ_CHR5_19_COLS_TAG].append(AXEQ_CHR5_19_GT_COL_NAME)
cols_tags[AXEQ_CHR5_19_COLS_TAG].append(AXEQ_CHR5_19_AF_COL_NAME)
cols_tags[AXEQ_CHR5_19_COLS_TAG].append(AXEQ_CHR5_19_PF_COL_NAME)
cols_tags[AXEQ_CHR5_19_COLS_TAG].append(AXEQ_CHR5_19_GF_COL_NAME)

# set columns associated with AXEQ_CHR9_COLS_TAG
cols_tags[AXEQ_CHR9_COLS_TAG] = []
cols_tags[AXEQ_CHR9_COLS_TAG].append(AXEQ_CHR9_WT_COL_NAME)
cols_tags[AXEQ_CHR9_COLS_TAG].append(AXEQ_CHR9_HET_COL_NAME)
cols_tags[AXEQ_CHR9_COLS_TAG].append(AXEQ_CHR9_HOM_COL_NAME)
cols_tags[AXEQ_CHR9_COLS_TAG].append(AXEQ_CHR9_OTH_COL_NAME)
cols_tags[AXEQ_CHR9_COLS_TAG].append(AXEQ_CHR9_NA_COL_NAME)
cols_tags[AXEQ_CHR9_COLS_TAG].append(AXEQ_CHR9_GT_COL_NAME)
cols_tags[AXEQ_CHR9_COLS_TAG].append(AXEQ_CHR9_AF_COL_NAME)
cols_tags[AXEQ_CHR9_COLS_TAG].append(AXEQ_CHR9_PF_COL_NAME)
cols_tags[AXEQ_CHR9_COLS_TAG].append(AXEQ_CHR9_GF_COL_NAME)

# set columns associated with WES294_OAF_CRCS_COLS_TAG
cols_tags[WES294_OAF_CRCS_COLS_TAG] = []
cols_tags[WES294_OAF_CRCS_COLS_TAG].append(WES294_OAF_CRCS_WT_COL_NAME)
cols_tags[WES294_OAF_CRCS_COLS_TAG].append(WES294_OAF_CRCS_HET_COL_NAME)
cols_tags[WES294_OAF_CRCS_COLS_TAG].append(WES294_OAF_CRCS_HOM_COL_NAME)
cols_tags[WES294_OAF_CRCS_COLS_TAG].append(WES294_OAF_CRCS_OTH_COL_NAME)
cols_tags[WES294_OAF_CRCS_COLS_TAG].append(WES294_OAF_CRCS_NA_COL_NAME)
cols_tags[WES294_OAF_CRCS_COLS_TAG].append(WES294_OAF_CRCS_GT_COL_NAME)
cols_tags[WES294_OAF_CRCS_COLS_TAG].append(WES294_OAF_CRCS_AF_COL_NAME)
cols_tags[WES294_OAF_CRCS_COLS_TAG].append(WES294_OAF_CRCS_PF_COL_NAME)
cols_tags[WES294_OAF_CRCS_COLS_TAG].append(WES294_OAF_CRCS_GF_COL_NAME)

# set columns associated with WES294_OAF_BRC_COLS_TAG
cols_tags[WES294_OAF_BRC_COLS_TAG] = []
cols_tags[WES294_OAF_BRC_COLS_TAG].append(WES294_OAF_BRCS_WT_COL_NAME)
cols_tags[WES294_OAF_BRC_COLS_TAG].append(WES294_OAF_BRCS_HET_COL_NAME)
cols_tags[WES294_OAF_BRC_COLS_TAG].append(WES294_OAF_BRCS_HOM_COL_NAME)
cols_tags[WES294_OAF_BRC_COLS_TAG].append(WES294_OAF_BRCS_OTH_COL_NAME)
cols_tags[WES294_OAF_BRC_COLS_TAG].append(WES294_OAF_BRCS_NA_COL_NAME)
cols_tags[WES294_OAF_BRC_COLS_TAG].append(WES294_OAF_BRCS_GT_COL_NAME)
cols_tags[WES294_OAF_BRC_COLS_TAG].append(WES294_OAF_BRCS_AF_COL_NAME)
cols_tags[WES294_OAF_BRC_COLS_TAG].append(WES294_OAF_BRCS_PF_COL_NAME)
cols_tags[WES294_OAF_BRC_COLS_TAG].append(WES294_OAF_BRCS_GF_COL_NAME)

# set columns associated with WES294_OAF_BRC_CRC_PROSTATE_COLS_TAG
cols_tags[WES294_OAF_BRC_CRC_PROSTATE_COLS_TAG] = []
cols_tags[WES294_OAF_BRC_CRC_PROSTATE_COLS_TAG].append(WES294_OAF_BRC_CRC_PROSTATE_WT_COL_NAME)
cols_tags[WES294_OAF_BRC_CRC_PROSTATE_COLS_TAG].append(WES294_OAF_BRC_CRC_PROSTATE_HET_COL_NAME)
cols_tags[WES294_OAF_BRC_CRC_PROSTATE_COLS_TAG].append(WES294_OAF_BRC_CRC_PROSTATE_HOM_COL_NAME)
cols_tags[WES294_OAF_BRC_CRC_PROSTATE_COLS_TAG].append(WES294_OAF_BRC_CRC_PROSTATE_OTH_COL_NAME)
cols_tags[WES294_OAF_BRC_CRC_PROSTATE_COLS_TAG].append(WES294_OAF_BRC_CRC_PROSTATE_NA_COL_NAME)
cols_tags[WES294_OAF_BRC_CRC_PROSTATE_COLS_TAG].append(WES294_OAF_BRC_CRC_PROSTATE_GT_COL_NAME)
cols_tags[WES294_OAF_BRC_CRC_PROSTATE_COLS_TAG].append(WES294_OAF_BRC_CRC_PROSTATE_AF_COL_NAME)
cols_tags[WES294_OAF_BRC_CRC_PROSTATE_COLS_TAG].append(WES294_OAF_BRC_CRC_PROSTATE_PF_COL_NAME)
cols_tags[WES294_OAF_BRC_CRC_PROSTATE_COLS_TAG].append(WES294_OAF_BRC_CRC_PROSTATE_GF_COL_NAME)

# set columns associated with WES294_OAF_CHEK2_COLS_TAG
cols_tags[WES294_OAF_CHEK2_COLS_TAG] = []
cols_tags[WES294_OAF_CHEK2_COLS_TAG].append(WES294_OAF_CHEK2_WT_COL_NAME)
cols_tags[WES294_OAF_CHEK2_COLS_TAG].append(WES294_OAF_CHEK2_HET_COL_NAME)
cols_tags[WES294_OAF_CHEK2_COLS_TAG].append(WES294_OAF_CHEK2_HOM_COL_NAME)
cols_tags[WES294_OAF_CHEK2_COLS_TAG].append(WES294_OAF_CHEK2_OTH_COL_NAME)
cols_tags[WES294_OAF_CHEK2_COLS_TAG].append(WES294_OAF_CHEK2_NA_COL_NAME)
cols_tags[WES294_OAF_CHEK2_COLS_TAG].append(WES294_OAF_CHEK2_GT_COL_NAME)
cols_tags[WES294_OAF_CHEK2_COLS_TAG].append(WES294_OAF_CHEK2_AF_COL_NAME)
cols_tags[WES294_OAF_CHEK2_COLS_TAG].append(WES294_OAF_CHEK2_PF_COL_NAME)
cols_tags[WES294_OAF_CHEK2_COLS_TAG].append(WES294_OAF_CHEK2_GF_COL_NAME)

# set columns associated with WES294_OAF_EARLYONSET_COLS_TAG
cols_tags[WES294_OAF_EARLYONSET_COLS_TAG] = []
cols_tags[WES294_OAF_EARLYONSET_COLS_TAG].append(WES294_OAF_EARLYONSET_WT_COL_NAME)
cols_tags[WES294_OAF_EARLYONSET_COLS_TAG].append(WES294_OAF_EARLYONSET_HET_COL_NAME)
cols_tags[WES294_OAF_EARLYONSET_COLS_TAG].append(WES294_OAF_EARLYONSET_HOM_COL_NAME)
cols_tags[WES294_OAF_EARLYONSET_COLS_TAG].append(WES294_OAF_EARLYONSET_OTH_COL_NAME)
cols_tags[WES294_OAF_EARLYONSET_COLS_TAG].append(WES294_OAF_EARLYONSET_NA_COL_NAME)
cols_tags[WES294_OAF_EARLYONSET_COLS_TAG].append(WES294_OAF_EARLYONSET_GT_COL_NAME)
cols_tags[WES294_OAF_EARLYONSET_COLS_TAG].append(WES294_OAF_EARLYONSET_AF_COL_NAME)
cols_tags[WES294_OAF_EARLYONSET_COLS_TAG].append(EST_KVOT_EARLYONSET_VS_BRC_COL_NAME)
cols_tags[WES294_OAF_EARLYONSET_COLS_TAG].append(EST_KVOT_EARLYONSET_VS_EXAC_NFE_COL_NAME)
cols_tags[WES294_OAF_EARLYONSET_COLS_TAG].append(EST_KVOT_EARLYONSET_VS_KG_EUR_COL_NAME)
cols_tags[WES294_OAF_EARLYONSET_COLS_TAG].append(EST_KVOT_EARLYONSET_VS_SWEGEN_COL_NAME)
cols_tags[WES294_OAF_EARLYONSET_COLS_TAG].append(WES294_OAF_EARLYONSET_PF_COL_NAME)
cols_tags[WES294_OAF_EARLYONSET_COLS_TAG].append(WES294_OAF_EARLYONSET_GF_COL_NAME)

# set columns associated with WES294_OAF_CRCS_COLS_TAG
cols_tags[WES294_OAF_FAMILIAL_CRCS_COLS_TAG] = []
cols_tags[WES294_OAF_FAMILIAL_CRCS_COLS_TAG].append(WES294_OAF_FAMILIAL_CRCS_WT_COL_NAME)
cols_tags[WES294_OAF_FAMILIAL_CRCS_COLS_TAG].append(WES294_OAF_FAMILIAL_CRCS_HET_COL_NAME)
cols_tags[WES294_OAF_FAMILIAL_CRCS_COLS_TAG].append(WES294_OAF_FAMILIAL_CRCS_HOM_COL_NAME)
cols_tags[WES294_OAF_FAMILIAL_CRCS_COLS_TAG].append(WES294_OAF_FAMILIAL_CRCS_OTH_COL_NAME)
cols_tags[WES294_OAF_FAMILIAL_CRCS_COLS_TAG].append(WES294_OAF_FAMILIAL_CRCS_NA_COL_NAME)
cols_tags[WES294_OAF_FAMILIAL_CRCS_COLS_TAG].append(WES294_OAF_FAMILIAL_CRCS_GT_COL_NAME)
cols_tags[WES294_OAF_FAMILIAL_CRCS_COLS_TAG].append(WES294_OAF_FAMILIAL_CRCS_AF_COL_NAME)
cols_tags[WES294_OAF_FAMILIAL_CRCS_COLS_TAG].append(WES294_OAF_FAMILIAL_CRCS_PF_COL_NAME)
cols_tags[WES294_OAF_FAMILIAL_CRCS_COLS_TAG].append(WES294_OAF_FAMILIAL_CRCS_GF_COL_NAME)

# set columns associated with MUTSTAT_DETAILS_COLS_TAG
cols_tags[MUTSTAT_DETAILS_COLS_TAG] = []
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR3_6_14_18_WT_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR3_6_14_18_HET_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR3_6_14_18_HOM_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR3_6_14_18_OTH_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR3_6_14_18_NA_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR3_6_14_18_GT_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR3_6_14_18_PF_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR5_19_WT_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR5_19_HET_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR5_19_HOM_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR5_19_OTH_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR5_19_NA_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR5_19_GT_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR5_19_PF_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR9_WT_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR9_HET_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR9_HOM_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR9_OTH_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR9_NA_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR9_GT_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(AXEQ_CHR9_PF_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_CRCS_WT_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_CRCS_HET_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_CRCS_HOM_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_CRCS_OTH_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_CRCS_NA_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_CRCS_GT_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_CRCS_PF_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_BRCS_WT_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_BRCS_HET_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_BRCS_HOM_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_BRCS_OTH_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_BRCS_NA_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_BRCS_GT_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_BRCS_PF_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_BRC_CRC_PROSTATE_WT_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_BRC_CRC_PROSTATE_HET_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_BRC_CRC_PROSTATE_HOM_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_BRC_CRC_PROSTATE_OTH_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_BRC_CRC_PROSTATE_NA_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_BRC_CRC_PROSTATE_GT_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_BRC_CRC_PROSTATE_PF_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_CHEK2_WT_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_CHEK2_HET_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_CHEK2_HOM_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_CHEK2_OTH_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_CHEK2_NA_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_CHEK2_GT_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_CHEK2_PF_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_EARLYONSET_WT_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_EARLYONSET_HET_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_EARLYONSET_HOM_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_EARLYONSET_OTH_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_EARLYONSET_NA_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_EARLYONSET_GT_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_EARLYONSET_PF_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_FAMILIAL_CRCS_WT_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_FAMILIAL_CRCS_HET_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_FAMILIAL_CRCS_HOM_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_FAMILIAL_CRCS_OTH_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_FAMILIAL_CRCS_NA_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_FAMILIAL_CRCS_GT_COL_NAME)
cols_tags[MUTSTAT_DETAILS_COLS_TAG].append(WES294_OAF_FAMILIAL_CRCS_PF_COL_NAME)

# set columns associated with LJB_SCORE_COLS_TAG
cols_tags[LJB_SCORE_COLS_TAG] = []
cols_tags[LJB_SCORE_COLS_TAG].append(CADD_RAW_COL_NAME)
cols_tags[LJB_SCORE_COLS_TAG].append(SIFT_SCORE_COL_NAME)
cols_tags[LJB_SCORE_COLS_TAG].append(POLYPHEN2_HDIV_SCORE_COL_NAME)
cols_tags[LJB_SCORE_COLS_TAG].append(POLYPHEN2_HVAR_SCORE_COL_NAME)
cols_tags[LJB_SCORE_COLS_TAG].append(LRT_SCORE_COL_NAME)
cols_tags[LJB_SCORE_COLS_TAG].append(MUTATIONTASTER_SCORE_COL_NAME)
cols_tags[LJB_SCORE_COLS_TAG].append(MUTATIONASSESSOR_SCORE_COL_NAME)
cols_tags[LJB_SCORE_COLS_TAG].append(FATHMM_SCORE_COL_NAME)
cols_tags[LJB_SCORE_COLS_TAG].append(RADIALSVM_SCORE_COL_NAME)
cols_tags[LJB_SCORE_COLS_TAG].append(LR_SCORE_COL_NAME)

# set columns associated with EXAC_OTH_COLS_TAG
cols_tags[EXAC_OTH_COLS_TAG] = []
cols_tags[EXAC_OTH_COLS_TAG].append(EXAC_AFR_COL_NAME)
cols_tags[EXAC_OTH_COLS_TAG].append(EXAC_AMR_COL_NAME)
cols_tags[EXAC_OTH_COLS_TAG].append(EXAC_EAS_COL_NAME)
cols_tags[EXAC_OTH_COLS_TAG].append(EXAC_FIN_COL_NAME)
cols_tags[EXAC_OTH_COLS_TAG].append(EXAC_OTH_COL_NAME)
cols_tags[EXAC_OTH_COLS_TAG].append(EXAC_SAS_COL_NAME)
cols_tags[EXAC_OTH_COLS_TAG].append(EXAC_NONTCGA_AFR_COL_NAME)
cols_tags[EXAC_OTH_COLS_TAG].append(EXAC_NONTCGA_AMR_COL_NAME)
cols_tags[EXAC_OTH_COLS_TAG].append(EXAC_NONTCGA_EAS_COL_NAME)
cols_tags[EXAC_OTH_COLS_TAG].append(EXAC_NONTCGA_FIN_COL_NAME)
cols_tags[EXAC_OTH_COLS_TAG].append(EXAC_NONTCGA_OTH_COL_NAME)
cols_tags[EXAC_OTH_COLS_TAG].append(EXAC_NONTCGA_SAS_COL_NAME)

# set columns associated with GNOMAD_OTH_COLS_TAG
cols_tags[GNOMAD_OTH_COLS_TAG] = []
cols_tags[GNOMAD_OTH_COLS_TAG].append(GNOMAD_GENOME_AFR_COL_NAME)
cols_tags[GNOMAD_OTH_COLS_TAG].append(GNOMAD_GENOME_AMR_COL_NAME)
cols_tags[GNOMAD_OTH_COLS_TAG].append(GNOMAD_GENOME_ASJ_COL_NAME)
cols_tags[GNOMAD_OTH_COLS_TAG].append(GNOMAD_GENOME_EAS_COL_NAME)
cols_tags[GNOMAD_OTH_COLS_TAG].append(GNOMAD_GENOME_FIN_COL_NAME)
cols_tags[GNOMAD_OTH_COLS_TAG].append(GNOMAD_GENOME_OTH_COL_NAME)

# set columns associated with SWEGEN_OTH_COLS_TAG
cols_tags[SWEGEN_OTH_COLS_TAG] = []
cols_tags[SWEGEN_OTH_COLS_TAG].append(SWEGEN_HET_COL_NAME)
cols_tags[SWEGEN_OTH_COLS_TAG].append(SWEGEN_HOM_COL_NAME)
cols_tags[SWEGEN_OTH_COLS_TAG].append(SWEGEN_HEMI_COL_NAME)
cols_tags[SWEGEN_OTH_COLS_TAG].append(SWEGEN_AC_COL_NAME)
cols_tags[SWEGEN_OTH_COLS_TAG].append(SWEGEN_GT_COL_NAME)
cols_tags[SWEGEN_OTH_COLS_TAG].append(SWEGEN_GF_COL_NAME)
cols_tags[SWEGEN_OTH_COLS_TAG].append(SWEGEN_PF_COL_NAME)

# set columns associated with EXAC_CONSTRAINT_COLS_TAG
cols_tags[EXAC_CONSTRAINT_COLS_TAG] = []
cols_tags[EXAC_CONSTRAINT_COLS_TAG].append(EXAC03_CONSTRAINT_EXP_SYN_COL_NAME)
cols_tags[EXAC_CONSTRAINT_COLS_TAG].append(EXAC03_CONSTRAINT_N_SYN_COL_NAME)
cols_tags[EXAC_CONSTRAINT_COLS_TAG].append(EXAC03_CONSTRAINT_SYN_Z_COL_NAME)
cols_tags[EXAC_CONSTRAINT_COLS_TAG].append(EXAC03_CONSTRAINT_EXP_MIS_COL_NAME)
cols_tags[EXAC_CONSTRAINT_COLS_TAG].append(EXAC03_CONSTRAINT_N_MIS_COL_NAME)
cols_tags[EXAC_CONSTRAINT_COLS_TAG].append(EXAC03_CONSTRAINT_MIS_Z_COL_NAME)
cols_tags[EXAC_CONSTRAINT_COLS_TAG].append(EXAC03_CONSTRAINT_EXP_LOF_COL_NAME)
cols_tags[EXAC_CONSTRAINT_COLS_TAG].append(EXAC03_CONSTRAINT_N_LOF_COL_NAME)
cols_tags[EXAC_CONSTRAINT_COLS_TAG].append(EXAC03_CONSTRAINT_PLI_COL_NAME)
EXAC03_CONSTRAINT_COL_NAMES = cols_tags[EXAC_CONSTRAINT_COLS_TAG]

cols_tags[KVOT_COLS_TAG] = []
cols_tags[KVOT_COLS_TAG].append(EST_KVOT_EARLYONSET_VS_BRC_COL_NAME)
cols_tags[KVOT_COLS_TAG].append(EST_KVOT_EARLYONSET_VS_SWEGEN_COL_NAME)
cols_tags[KVOT_COLS_TAG].append(EST_KVOT_EARLYONSET_VS_EXAC_NFE_COL_NAME)
cols_tags[KVOT_COLS_TAG].append(EST_KVOT_EARLYONSET_VS_KG_EUR_COL_NAME)
EST_KVOT_COLS = cols_tags[KVOT_COLS_TAG]


# set columns associated with UNKNOWN_COLS_TAG
cols_tags[UNKNOWN_COLS_TAG] = []
#cols_tags[UNKNOWN_COLS_TAG].append(GENOMICSUPERDUPS_COL_NAME)
#cols_tags[UNKNOWN_COLS_TAG].append(CG69_COL_NAME)
#cols_tags[UNKNOWN_COLS_TAG].append(NCI60_COL_NAME)
cols_tags[UNKNOWN_COLS_TAG].append(VEST3_SCORE_COL_NAME)
cols_tags[UNKNOWN_COLS_TAG].append(GERP_RS_COL_NAME)
cols_tags[UNKNOWN_COLS_TAG].append(PHYLOP46WAY_PLACENTAL_COL_NAME)
cols_tags[UNKNOWN_COLS_TAG].append(PHYLOP100WAY_VERTEBRATE_COL_NAME)

# assign all tags to all related columns
for cols_tag in cols_tags:
    col_names = cols_tags[cols_tag]
    for col_name in col_names:
        ALL_MUTREP_ANNO_COLS[col_name].append(cols_tag)

TMP_HEADER_CORRECTIONS = []
TMP_HEADER_CORRECTIONS.append(WES294_OAF_BRCS_WT_COL_NAME + ":" + "BRCS_WT")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_BRCS_HET_COL_NAME + ":" + "BRCS_HET")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_BRCS_HOM_COL_NAME + ":" + "BRCS_HOM")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_BRCS_OTH_COL_NAME + ":" + "BRCS_OTH")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_BRCS_NA_COL_NAME + ":" + "BRCS_NA")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_BRCS_GT_COL_NAME + ":" + "BRCS_GT")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_BRCS_PF_COL_NAME + ":" + "BRCS_PF")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_BRCS_AF_COL_NAME + ":" + "BRCS_AF")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_BRCS_GF_COL_NAME + ":" + "BRCS_GF")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_CRCS_WT_COL_NAME + ":" + "CRCS_WT")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_CRCS_HET_COL_NAME + ":" + "CRCS_HET")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_CRCS_HOM_COL_NAME + ":" + "CRCS_HOM")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_CRCS_OTH_COL_NAME + ":" + "CRCS_OTH")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_CRCS_NA_COL_NAME + ":" + "CRCS_NA")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_CRCS_GT_COL_NAME + ":" + "CRCS_GT")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_CRCS_PF_COL_NAME + ":" + "CRCS_PF")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_CRCS_AF_COL_NAME + ":" + "CRCS_AF")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_CRCS_GF_COL_NAME + ":" + "CRCS_GF")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_BRC_CRC_PROSTATE_WT_COL_NAME + ":" + "ALL_EXOME_WT")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_BRC_CRC_PROSTATE_HET_COL_NAME + ":" + "ALL_EXOME_HET")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_BRC_CRC_PROSTATE_HOM_COL_NAME + ":" + "ALL_EXOME_HOM")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_BRC_CRC_PROSTATE_OTH_COL_NAME + ":" + "ALL_EXOME_OTH")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_BRC_CRC_PROSTATE_NA_COL_NAME + ":" + "ALL_EXOME_NA")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_BRC_CRC_PROSTATE_GT_COL_NAME + ":" + "ALL_EXOME_GT")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_BRC_CRC_PROSTATE_PF_COL_NAME + ":" + "ALL_EXOME_PF")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_BRC_CRC_PROSTATE_AF_COL_NAME + ":" + "ALL_EXOME_AF")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_BRC_CRC_PROSTATE_GF_COL_NAME + ":" + "ALL_EXOME_GF")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_CHEK2_WT_COL_NAME + ":" + "CHEK2_WT")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_CHEK2_HET_COL_NAME + ":" + "CHEK2_HET")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_CHEK2_HOM_COL_NAME + ":" + "CHEK2_HOM")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_CHEK2_OTH_COL_NAME + ":" + "CHEK2_OTH")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_CHEK2_NA_COL_NAME + ":" + "CHEK2_NA")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_CHEK2_GT_COL_NAME + ":" + "CHEK2_GT")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_CHEK2_PF_COL_NAME + ":" + "CHEK2_PF")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_CHEK2_AF_COL_NAME + ":" + "CHEK2_AF")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_CHEK2_GF_COL_NAME + ":" + "CHEK2_GF")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_EARLYONSET_WT_COL_NAME + ":" + "EARLYONSET_WT")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_EARLYONSET_HET_COL_NAME + ":" + "EARLYONSET_HET")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_EARLYONSET_HOM_COL_NAME + ":" + "EARLYONSET_HOM")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_EARLYONSET_OTH_COL_NAME + ":" + "EARLYONSET_OTH")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_EARLYONSET_NA_COL_NAME + ":" + "EARLYONSET_NA")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_EARLYONSET_GT_COL_NAME + ":" + "EARLYONSET_GT")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_EARLYONSET_PF_COL_NAME + ":" + "EARLYONSET_PF")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_EARLYONSET_AF_COL_NAME + ":" + "EARLYONSET_AF")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_EARLYONSET_GF_COL_NAME + ":" + "EARLYONSET_GF")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_FAMILIAL_CRCS_WT_COL_NAME + ":" + "FAMILIAL_CRCS_WT")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_FAMILIAL_CRCS_HET_COL_NAME + ":" + "FAMILIAL_CRCS_HET")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_FAMILIAL_CRCS_HOM_COL_NAME + ":" + "FAMILIAL_CRCS_HOM")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_FAMILIAL_CRCS_OTH_COL_NAME + ":" + "FAMILIAL_CRCS_OTH")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_FAMILIAL_CRCS_NA_COL_NAME + ":" + "FAMILIAL_CRCS_NA")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_FAMILIAL_CRCS_GT_COL_NAME + ":" + "FAMILIAL_CRCS_GT")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_FAMILIAL_CRCS_PF_COL_NAME + ":" + "FAMILIAL_CRCS_PF")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_FAMILIAL_CRCS_AF_COL_NAME + ":" + "FAMILIAL_CRCS_AF")
TMP_HEADER_CORRECTIONS.append(WES294_OAF_FAMILIAL_CRCS_GF_COL_NAME + ":" + "FAMILIAL_CRCS_GF")
TMP_HEADER_CORRECTIONS.append(EXAC03_CONSTRAINT_EXP_SYN_COL_NAME + ":" + "Exp Syn(ExAC)")
TMP_HEADER_CORRECTIONS.append(EXAC03_CONSTRAINT_N_SYN_COL_NAME + ":" + "Obs Syn(ExAC)")
TMP_HEADER_CORRECTIONS.append(EXAC03_CONSTRAINT_SYN_Z_COL_NAME + ":" + "Syn z(ExAC)")
TMP_HEADER_CORRECTIONS.append(EXAC03_CONSTRAINT_EXP_MIS_COL_NAME + ":" + "Exp Mis(ExAC)")
TMP_HEADER_CORRECTIONS.append(EXAC03_CONSTRAINT_N_MIS_COL_NAME + ":" + "Obs Mis(ExAC)")
TMP_HEADER_CORRECTIONS.append(EXAC03_CONSTRAINT_MIS_Z_COL_NAME + ":" + "Mis Z(ExAC)")
TMP_HEADER_CORRECTIONS.append(EXAC03_CONSTRAINT_EXP_LOF_COL_NAME + ":" + "Exp LoF(ExAC)")
TMP_HEADER_CORRECTIONS.append(EXAC03_CONSTRAINT_N_LOF_COL_NAME + ":" + "Obs LoF(ExAC)")
TMP_HEADER_CORRECTIONS.append(EXAC03_CONSTRAINT_PLI_COL_NAME + ":" + "PLI(ExAC)")
TMP_HEADER_CORRECTIONS.append(GNOMAD_GENOME_ALL_COL_NAME + ":" + "gnomAD_ALL")
TMP_HEADER_CORRECTIONS.append(GNOMAD_GENOME_AFR_COL_NAME + ":" + "gnomAD_AFR")
TMP_HEADER_CORRECTIONS.append(GNOMAD_GENOME_AMR_COL_NAME + ":" + "gnomAD_AMR")
TMP_HEADER_CORRECTIONS.append(GNOMAD_GENOME_ASJ_COL_NAME + ":" + "gnomAD_ASJ")
TMP_HEADER_CORRECTIONS.append(GNOMAD_GENOME_EAS_COL_NAME + ":" + "gnomAD_EAS")
TMP_HEADER_CORRECTIONS.append(GNOMAD_GENOME_FIN_COL_NAME + ":" + "gnomAD_FIN")
TMP_HEADER_CORRECTIONS.append(GNOMAD_GENOME_NFE_COL_NAME + ":" + "gnomAD_NFE")
TMP_HEADER_CORRECTIONS.append(GNOMAD_GENOME_OTH_COL_NAME + ":" + "gnomAD_OTH")

DFLT_HEADER_CORRECTIONS = ",".join(TMP_HEADER_CORRECTIONS)
