#!/bin/bash
source $PYCMM/bash/cmm_functions.sh

script_name=$(basename $0)
params="$@"

usage=$(
cat <<EOF
usage:
$0 [OPTION]
option:
-k {name}          dataset name (required)
-d {folder}        input folder (required)
-o {file}          output file name (required)
EOF
)

while getopts ":k:d:o:" OPTION; do
  case "$OPTION" in
    k)
      dataset_name="$OPTARG"
      ;;
    d)
      input_folder="$OPTARG"
      ;;
    o)
      out_file="$OPTARG"
      ;;
    *)
      die "unrecognized option from executing: $0 $@"
      ;;
  esac
done

[ ! -z $dataset_name ] || die "Please specify dataset name (-k)"
[ ! -z $input_folder ] || die "Please specify input folder (-d)"
[ ! -z $out_file ] || die "Plesae specify output file name (-o)"
[ -d $input_folder ] || die "$input_folder is not a valid folder name"

## ****************************************  display configuration  ****************************************
new_section_txt "S T A R T <$script_name>"
info_msg
info_msg "parameters"
info_msg "  $params"
info_msg
info_msg "description"
info_msg "  A script to concat mutations stat generated by pyCMM"
info_msg
info_msg
## display required configuration
info_msg "overall configuration"
display_param "dataset name (-k)" "$dataset_name"
display_param "input folder (-d)" "$input_folder"
display_param "output file (-o)" "$out_file"

# ****************************************  executing  ****************************************

new_section_txt "E X E C U T I N G"

out_dir=`dirname $out_file`
mkdir -p $out_dir

# create header
head -1 $input_folder/$dataset_name"_1.stat" | sed 's/_1_/_/g' > $out_file

for chrom in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 MT X Y
do
    input_stat_file=$input_folder/$dataset_name"_"$chrom.stat
    if [ -f $input_stat_file ]
    then
        info_msg "Processing stat file: $input_stat_file"
        grep -v "^#" $input_stat_file | sort -k2,2n -k4,4 -k5,5 >> $out_file
    fi
done

#---------- idx stat file --------------
idx_stat_file="$out_file.idx"
idx_cmd="$PYCMM/bash/compileAnnnovarIndex.pl"
idx_cmd+=" $out_file"
idx_cmd+=" 1000"
idx_cmd+=" > $idx_stat_file"
eval_cmd "$idx_cmd"
#---------- idx stat file --------------

new_section_txt "F I N I S H <$script_name>"
